/* BIOL 40B — Lecture Exam 2 · "Explain it like I'm 5"
   A second, plain-language explanation for every question, shown only if you ask for it.

   The `why` field on each question is the exam-level explanation — correct terminology,
   the detail you need on the test. This is the other thing: no jargon, concrete pictures,
   the version you'd give someone who has never taken a biology class. If the technical
   explanation didn't land, this one is a different road to the same place.

   Keys are the question's tracking id: "A12" (Form A #12), "B7" (Form B #7),
   "H3" (histology #3) — the same ids used everywhere else, so the drill, the starred set
   and the review queue all find the right entry. */
const ELI5 = {

/* ===================== FORM A ===================== */
A1: `Blood is a delivery truck, a thermostat, and a security guard all in one. It hauls stuff around, keeps your insides at the right temperature and pH, and scabs over cuts while fighting germs.`,
A2: `Spin blood in a tube and it separates like salad dressing. The heavy red sludge at the bottom is the red cells — a bit under half the tube. The clear yellowish liquid on top is plasma, which is mostly water.`,
A3: `Red cells are the most common thing in blood by miles, like grains of sand on a beach. Platelets are much rarer, and white cells are the rarest of the three — you'd have to hunt for one.`,
A4: `Albumin is the moving guy of the blood. It's the most common protein in there, it carries small stuff around piggyback, and it holds water inside your blood vessels so the water doesn't leak out into your tissues.`,
A5: `Blood typing is a clumping test. You drip two different liquids on the blood and watch. Whichever one makes it curdle tells you what kind of blood it is. Clump with the first only = type A.`,
A6: `A red blood cell is a delivery van with the engine removed. No engine means it can't burn the oxygen it's delivering — so all the oxygen actually reaches the customer. It's also squished flat like a pillow so more of it touches the air.`,
A7: `Hemoglobin is a taxi with four seats. Each seat has an iron hook, and each hook grabs exactly one oxygen. So one taxi carries four passengers.`,
A8: `Your kidneys are the oxygen alarm. If oxygen gets low they yell at your bone marrow to build more red cells. Broken kidneys can't yell, so the marrow never gets the message and you run low on red cells.`,
A9: `Your stomach makes a special helper that lets you absorb vitamin B12, and B12 is what cells need to divide. Without it, new red cells keep growing but can never split — so you end up with a few giant blobs instead of lots of normal cells.`,
A10: `These red cells are fine until oxygen runs low — then they bend into a banana shape. Bananas don't roll through narrow tubes like round pillows do, so they jam up in tiny blood vessels and pop. That hurts, and the tissue past the jam doesn't get its oxygen.`,
A11: `Too many red cells makes blood thick, like syrup instead of water. Syrup is hard to pump and moves slowly, so everything backs up.`,
A12: `Neutrophils are the police who show up first to almost every call. Out of every ten white cells you find, six or seven are them.`,
A13: `Eosinophils are the pest-control crew — they handle worms and allergy messes. Basophils are the ones who dump out the chemical that makes you puffy, itchy and sneezy.`,
A14: `A platelet isn't a whole cell — it's a chip that broke off a much bigger cell in your bone marrow. Think of a big cookie crumbling and the crumbs going out to plug leaks.`,
A15: `A healthy blood vessel is lined with something slippery, like a non-stick pan, and there's no rough spot for platelets to grab. Cut it and you expose rough threads underneath — now platelets have something to stick to, like velcro.`,
A16: `Three things happen when you get cut, in order. The pipe squeezes itself narrower to slow the leak. Platelets pile into the hole like sandbags. Then real cement sets around the sandbags.`,
A17: `Thrombin is the cement mixer. It takes a soluble ingredient floating in your blood and turns it into sticky threads that web across the hole and harden the plug.`,
A18: `A clot that stays where it formed is one thing. Break loose and float downstream and it's another. Get stuck somewhere and block the pipe, and that's the disaster. Three stages, three names.`,
A19: `Your blood carries little guard dogs trained to attack any blood that isn't yours. Give a type A person type B blood and the guards attack immediately, clumping the donated cells into blobs that jam your vessels.`,

A20: `Your heart sits in the middle of your chest, not on the left like people say. It's tilted, though — the pointy bottom tip aims down toward your left hip, which is why you feel your heartbeat over on that side.`,
A21: `The heart comes wrapped like a present. There's a tough outer bag, then two slippery inner layers with a little fluid between them so the heart can slide as it beats instead of scraping.`,
A22: `Fluid is filling up the bag around the heart and squeezing it, like a hand closing around a water balloon. A squeezed heart can't fill up, so it can't pump. You fix it by sticking a needle in and draining the bag.`,
A23: `The top two rooms of the heart are the waiting rooms — thin, floppy, and they barely push at all. They just collect blood and drop it into the powerful rooms below.`,
A24: `The valve flaps have little strings tied to the floor, like a parachute's cords. When pressure slams up against the flaps, the strings stop them from flipping inside out.`,
A25: `Three pipes dump into the top-right room: one big vein bringing blood down from your head and arms, one big vein bringing it up from your legs and belly, and one small one draining the heart's own walls.`,
A26: `Blood does a figure-eight. Right side of the heart sends it to the lungs to pick up oxygen, lungs send it back to the left side, and the left side blasts it out to the whole body. Then it comes back to the right side and goes around again.`,
A27: `The heart is a pump that also needs feeding, so it taps its own output — two little pipes branch off right where blood leaves. And it feeds itself while it's relaxed, because a squeezing muscle pinches its own pipes shut.`,
A28: `Chest pain that comes with exertion and goes away with rest means the muscle is briefly starved but survives. A blockage that doesn't let go kills that patch of muscle, and dead heart muscle gets replaced by scar — and scar doesn't squeeze.`,
A29: `There's a little patch of tissue in the top right of your heart that ticks on its own, like a metronome nobody has to wind. It sets the beat, about 60–100 times a minute, with no help from your brain.`,
A30: `The signal deliberately pauses at a checkpoint before it reaches the bottom rooms. That pause lets the top rooms finish emptying, so the bottom rooms are full before they squeeze. Squeeze too early and you'd be pumping a half-empty chamber.`,
A31: `The electrical signal follows one road every time: starts at the metronome up top, pauses at the checkpoint, runs down the middle wall, then fans out through the bottom rooms.`,
A32: `Heart muscle cells are short, branchy, and glued end-to-end with special connectors that let the electrical signal jump straight from one cell into the next. So the whole wall fires as one unit instead of cell by cell. And it needs oxygen constantly — it can't hold its breath.`,

A33: `Most heart cells wait to be told to fire. A tiny few can't sit still — they slowly leak charge until they trip their own trigger, over and over. Those are the ones that set the beat.`,
A34: `A normal nerve signal is a quick spike, up and straight back down. Heart muscle holds the top of the spike for a while — calcium creeps in and props it up, like holding a note instead of tapping a key.`,
A35: `Regular muscles can be zapped so fast they lock up in one long cramp. Your heart is built so that can't happen — after each beat it's completely deaf to new signals for a while. A cramping heart would never refill.`,
A36: `An EKG is a squiggle that shows electrical activity, not squeezing. The little first bump is the electricity spreading through the top two rooms right before they squeeze.`,
A37: `The big spike is electricity sweeping through the bottom rooms. The gentle bump right after is those same rooms resetting themselves electrically so they can do it again.`,
A38: `That stretch of the squiggle is normally a flat line because nothing electrical is changing right then. If it's pushed up off the baseline, part of the heart muscle is starving or dying. That's the classic heart-attack sign.`,
A39: `Between beats, the doors between the top and bottom rooms are open so blood can drain down. The doors leading out to the big arteries are shut, so nothing escapes while it's filling.`,
A40: `The room is squeezing hard but every door is still shut, so no blood goes anywhere yet — pressure just builds, like pushing on a closed door. The instant pressure beats what's on the other side, the door pops open.`,
A41: `The "lub-dub" is doors slamming, not blood swooshing. The first sound is the inner doors slamming as the squeeze starts. The second is the outer doors slamming as the squeeze ends.`,
A42: `The room holds about 135 mL when completely full and about 65 mL after it squeezes. So it pushed out about 70 mL. Full minus leftover equals what got delivered — and notice it never empties all the way.`,
A43: `Something "positive chronotropic" speeds up your heart. The gas pedal. Adrenaline-type signals do it — that's why your heart pounds when you're scared.`,
A44: `Multiply how many times it beats per minute by how much it squirts each beat. 75 beats × 70 mL = 5,250 mL, so a bit over five liters a minute. Your whole blood supply, once a minute.`,
A45: `Stretch a rubber band further and it snaps back harder. When more blood comes back and fills the heart fuller, the walls stretch more and snap back harder, so more goes out.`,
A46: `Afterload is how hard the door out is to push open. With high blood pressure the door is heavy, so the heart wastes effort just getting it open and less blood actually gets through.`,
A47: `Potassium leaking around outside the cells makes it harder for heart cells to build up a charge, so the beat gets sluggish. Calcium does the opposite. Fear, fever and running all speed you up.`,
A48: `The checkpoint between the top and bottom rooms is broken, so the signal can't get down. The bottom rooms fall back on their own slow backup rhythm — about 30 beats a minute, way too slow.`,

A49: `Blood goes out through big pipes that branch into smaller pipes, then into pipes so tiny they're one cell thick — that's where the actual dropping-off happens. Then small pipes merge into bigger ones on the way home.`,
A50: `The middle layer of a vessel wall is the muscle layer. Squeeze it and the pipe narrows; relax it and the pipe widens. That's how your body redirects blood to where it's needed.`,
A51: `Capillary walls are one cell thick — basically tissue paper. That's the only reason food and oxygen can slip out to your cells and trash can slip back in. Thick-walled pipes are just plumbing.`,
A52: `Veins are the low-pressure return road: floppier walls, and little one-way flaps inside so blood can't slide backward on its way uphill. Arteries don't need flaps because the pressure is already shoving everything forward.`,
A53: `The huge pipes near the heart are stretchy — they balloon out with each heartbeat and squeeze back between beats, which smooths a series of jolts into a steady stream. Medium pipes are more muscular and act like off-ramps to specific places.`,
A54: `At the start of a capillary the pushing pressure wins, so watery fluid squirts out into the tissue. Think of a leaky hose — pressure inside pushes water out through the seams.`,
A55: `Small stuff like oxygen just slips straight through the wall. Big stuff like insulin is too fat to slip through, so the cell wraps it in a bubble, carries it across, and dumps it out the other side.`,
A56: `Flow depends on two things fighting: how hard you're pushing, and how much the pipes resist. More push, more flow. More resistance, less flow. Same as water through a garden hose.`,
A57: `One capillary is tiny, but there are billions of them side by side, so together they're a much wider channel than the artery feeding them. Water slows way down when a narrow stream opens into a wide one — and slow is exactly what you want, because slow means time to unload.`,
A58: `Three things make blood hard to push: narrow pipes, thick blood, and long pipes. Narrowness matters most, and it's the one your body can change instantly.`,
A59: `Squeeze every small pipe in your body a little tighter and pressure shoots up everywhere. Same as pinching a hose — the water behind the pinch pushes harder.`,
A60: `There are stretch sensors in your vessel walls that feel pressure like a hand feeling a balloon. When you stand and pressure drops, they notice the balloon got softer and tell a control center in your brainstem to fix it.`,
A61: `The top number is the peak pressure when the heart squeezes; the bottom number is the resting pressure between squeezes. Subtract them for pulse pressure: 118 − 76 = 42.`,
A62: `Shock is the pump failing to keep up, so your body abandons the outskirts to save the core. Skin goes cold, pale and clammy because blood was pulled away from it. Heart races but the pulse feels weak and thready, pressure drops, thinking goes fuzzy, and you stop making much pee.`,
A63: `Negative feedback is a thermostat. Pressure drops, the body notices and cranks things up, pressure comes back to normal — and then it stops cranking. The fix turns itself off once it worked.`,
A64: `Blood pressure has bands, like speed limits. Under 120 over 80 is fine. This person is at 148 over 94, which lands them in the first serious band — not an emergency, but not okay either.`,

A65: `Most of your airway is just hallway — it moves air but nothing happens in it. Only the last little grape-cluster air sacs at the very end actually trade oxygen for carbon dioxide.`,
A66: `Two different swaps get the same name with different labels. "External" is the swap at the lungs — air to blood. "Internal" is the swap out at your muscles and organs — blood to cells.`,
A67: `Your nose is an air-conditioner and a filter. It warms and dampens the air, catches dust in snot, gives your voice its tone, and it's where your sense of smell lives.`,
A68: `The voice box has a little flap on top that folds down over the airway when you swallow, so food goes down the food tube instead of the air tube. The gap between your vocal cords is the actual hole air goes through.`,
A69: `Your windpipe is lined with sticky cells that make snot, plus tiny hairs that sweep the snot upward like an escalator carrying trash out. And it's braced with C-shaped rings of stiff cartilage — open at the back so your food tube can bulge when you swallow.`,
A70: `Going deeper into the lungs, the tubes trade their stiff rings for muscle. That's the whole reason an asthma attack is possible — the deep tubes can squeeze themselves shut, and the big stiff ones can't.`,
A71: `Wet surfaces stick together — that's why a wet plastic bag collapses on itself. Your air sacs make a soapy substance that stops them sticking shut when you exhale.`,
A72: `Each lung is wrapped in two slippery sheets with fluid between, so it slides instead of scraping as you breathe. The right lung has three chunks and the left only two, because the heart takes up space on the left.`,
A73: `Breathing in is making your chest bigger. The dome under your lungs flattens down and your ribs lift, and the extra space means lower pressure inside than outside — so air rushes in on its own. You don't suck air in; you make room and it falls in.`,
A74: `There's a permanent gentle vacuum in the thin space around each lung, and it's what keeps the lung stretched open against its own urge to shrink. Poke a hole and let air in, the vacuum is gone, and the lung crumples like a deflated balloon.`,
A75: `Vital capacity is every bit of air you can actually move: a normal breath, plus everything extra you could suck in, plus everything extra you could blow out. Add those three.`,
A76: `Add the three movable amounts — 500 + 3,100 + 1,200 — and you get 4,800 mL, the most air you can shift. Then add the 1,200 you can never blow out no matter how hard you try, and the lungs hold 6,000 total.`,
A77: `Each gas moves from wherever it's crowded to wherever it's not, and it ignores the other gas completely. Oxygen is crowded in the air sac and scarce in the blood, so it goes in. Carbon dioxide is crowded in the blood and scarce in the sac, so it goes out. Both at once, opposite directions.`,
A78: `Most carbon dioxide doesn't ride on the taxi at all — it gets converted into a dissolved form and just floats in the liquid part of the blood. About seven out of ten travel that way.`,
A79: `You don't breathe because you're low on oxygen — you breathe because carbon dioxide is building up. It makes your blood slightly acidic, your brainstem notices, and it makes you breathe harder. That's why holding your breath eventually forces you to gasp.`,
A80: `Laryngitis is swollen vocal cords. Swollen cords can't vibrate properly, so your voice goes rough and croaky, or nearly disappears.`,

/* ===================== FORM B ===================== */
B1: `Getting too hot, your body sends blood to the surface so heat can escape through your skin — that's why you go red when you exercise. Blood is the heat delivery system, and a spot in your brain is the thermostat setting the target.`,
B2: `Blood is a bit more than half liquid, and that liquid is mostly plain water with things dissolved in it. The rest of the tube is cells.`,
B3: `Only white cells are complete cells with a full command center. Red cells threw theirs out to make room for cargo. Platelets were never whole cells at all — they're chips off a bigger one.`,
B4: `Electrolytes are just salts dissolved in your blood — the stuff in sports drinks. Sodium, potassium, calcium and friends.`,
B5: `Albumin holds water inside your vessels, like a sponge keeping water in place. Lose it and water seeps out into your tissues, so you puff up and swell.`,
B6: `Red cells carry a tool that converts carbon dioxide into a dissolved form that travels easily in liquid. That's the trick that lets most of your carbon dioxide hitch a ride in the plasma instead of clogging up the taxi seats.`,
B7: `Carbon monoxide grabs the oxygen hooks on hemoglobin and won't let go — it's a squatter in the taxi seats. The taxi drives around full but carrying nothing useful, so you suffocate while breathing normally. That's what makes it so sneaky.`,
B8: `A red cell works for about four months, then gets eaten and recycled by your spleen or liver. It has no repair kit, so it wears out and gets retired.`,
B9: `No iron means you can't build the red pigment that carries oxygen. So the cells come out undersized and washed-out looking, like watered-down paint.`,
B10: `Radiation wrecked the factory, not one product line. So you're short on red cells, short on the clot-plugging chips, and short on germ-fighters, all at once. Three problems from one broken factory.`,
B11: `A slow leak is still a leak. You can pour in all the blood you want, but until you patch the hole in the stomach it keeps draining out. Fix the leak first.`,
B12: `Clumping in both test drops means both markers are on the cells — that's the type that has everything. And because your body never attacks its own markers, that person's blood has no attack dogs at all, so they can safely receive anyone's blood.`,
B13: `Monocytes are rookies in the bloodstream — they only become the real garbage-eating giants after they leave the blood and settle into tissue. Lymphocytes are the specialists: one makes targeted weapons, one directs the operation, one just kills anything suspicious.`,
B14: `The first platelets to arrive send up a flare that calls in more platelets and tells the pipe to squeeze tighter. It snowballs on purpose — that's how a tiny plug becomes a real one fast.`,
B15: `Once the wall is repaired, the scab has to come off. Your body switches on a pair of scissors that chop up the sticky threads, and the clot dissolves away.`,
B16: `There are two ways to start the clotting chain — one triggered by rough spots inside the damaged vessel, one triggered by chemicals leaking out of mashed tissue. Different starting lines, same finish line.`,
B17: `Before anything else, the cut pipe clamps itself narrower. Squeezing a hose slows the spill immediately, and it buys time for the slower repairs.`,
B18: `This person is almost out of the chips that plug leaks, so tiny vessels seep everywhere and leave pinprick purple dots all over the skin. Not bruises from bumping — leaks from having nothing to plug them.`,
B19: `Type O cells are blank — no markers on them at all. But the plasma carries attack dogs for both markers, so an O person can only receive O blood, even though their blank cells are safe to give to lots of people.`,
B20: `The middle layer of the heart wall is the actual muscle — the thick meaty part that does the squeezing. The layers on either side are just wrapping and lining.`,
B21: `The bottom two rooms are the real pumps: thick walls, ridged insides, and little muscle stubs with strings running up to hold the valves shut. All the power is down here.`,
B22: `The door out of the right pump has three half-moon flaps that catch backflow like three cupped hands. No strings on these — they don't need any, because backflow just presses them together.`,
B23: `The door on the left side between the top and bottom rooms has two flaps. The right side has three. That's literally where the names come from.`,
B24: `Stiff, narrowed door: the heart has to shove much harder to get blood through a smaller opening. Leaky door: blood slides back in, so the heart keeps re-pumping the same blood. Two different failures, both exhausting.`,
B25: `One loop goes heart → lungs → heart, just to pick up oxygen. The other goes heart → everywhere else → heart, to drop it off. Two loops, one pump in the middle running both.`,
B26: `The left side has to push blood to your toes and your brain; the right side only has to push it to the lungs next door. Longer trip, more muscle needed.`,
B27: `Four pipes bring oxygen-rich blood back from the lungs into the top-left room. They're called veins because they head toward the heart — but unlike every other vein, they're full of fresh oxygenated blood.`,
B28: `The heart's own supply pipes have little bridges connecting them. If one route narrows, blood can partly detour around it. Pipes with no bridges are dead ends — block one and everything past it dies.`,
B29: `Almost every heart cell is a worker that squeezes but has to be told when. A tiny handful are timekeepers that fire on their own and don't squeeze at all. The timekeepers boss the workers, and no message from the brain is required.`,
B30: `The bottom of the heart gets the signal first, and these fibers spread it up through the walls. So the squeeze rolls from the bottom upward — which pushes blood up toward the exits, like squeezing a toothpaste tube from the end.`,
B31: `Some patch of muscle gets twitchy and starts firing faster than the real metronome, so it hijacks the beat. Too much coffee can do it. You feel it as a skipped or extra thump.`,
B32: `The connectors between heart cells have little tunnels, so an electrical signal walks straight from one cell into the next without stopping. That's why the whole wall contracts as one piece instead of a ripple of individuals.`,
B33: `The conduction system is the wiring that keeps the squeeze in the right order and on time. Once it fires, the signal spreads cell to cell through built-in tunnels — no wires needed past the starting point.`,
B34: `A neighbor cell passes the signal over, sodium floods in and the cell flips positive, then calcium creeps in and holds it there a while, and finally potassium leaves and the cell resets. Flip, hold, reset.`,
B35: `The electrical signal dives into little tunnels in the cell and lets a bit of calcium in. That bit of calcium triggers a much bigger calcium dump from the cell's own storage closet, and the calcium is what actually makes the fibers slide and shorten.`,
B36: `An EKG is like listening to a stadium from outside — you can hear the crowd surge and tell roughly what happened, but you can't hear one person. It shows changes in electrical activity, not the actual voltage of any single cell.`,
B37: `To get heart rate, measure from one big spike to the next big spike — that's one full cycle, so you count how many fit in a minute. The stretch from the little first bump to the big spike includes the deliberate pause at the checkpoint.`,
B38: `Electricity always comes before movement. The big spike is the bottom rooms getting the electrical order; the squeeze follows a moment later. Same as a light switch — flip, then the bulb lights.`,
B39: `One cardiac cycle is one complete heartbeat, from filling through squeezing and back. And the top rooms must finish their squeeze before the bottom rooms start theirs — otherwise you'd be fighting yourself.`,
B40: `The exit doors are open, the entry doors are shut, and blood is leaving — so the room is emptying. One-way traffic, out only.`,
B41: `Valves have no motors. They're swinging doors that open whichever way the pressure is pushing, so blood can only go one direction. Higher pressure behind them, they open; higher pressure in front, they slam shut.`,
B42: `When the exit door slams, blood bouncing off it makes the pressure in the big artery blip upward for a moment. That blip is a little notch on the graph, and the slam itself is the second "dub" you hear.`,
B43: `You have a brake pedal and a gas pedal on your heart. The brake makes heart cells harder to trigger, so the beat slows. The gas makes them easier to trigger, so it speeds up. Both are always partly pressed.`,
B44: `Cardiac output is how much your heart moves in a minute — beats per minute times the amount per beat. Cardiac reserve is your headroom: the difference between idling and flat out. Athletes have way more headroom.`,
B45: `Both drugs mess with calcium inside heart cells, and calcium is what determines how hard the squeeze is. More calcium, stronger squeeze. Less calcium, weaker squeeze. Neither one changes the rate — just the strength.`,
B46: `Less blood coming back means the heart doesn't fill as full. A less-full balloon stretches less and snaps back weaker, so less goes out per beat. That's why heavy bleeding drops your blood pressure.`,
B47: `Getting older, your resting-and-maximum heart rate drift down. Exercise and fever both push it up. So a kid running around has a much faster heartbeat than a grandparent sitting still.`,
B48: `Under 60 beats a minute is "too slow"; over 100 is "too fast." This person is at 48, so they're in the too-slow camp — which is why they're dizzy, since a slow pump doesn't get enough blood up to the brain.`,
B49: `Going out, pipes keep branching into smaller ones. Coming back, small ones keep merging into bigger ones. The tiny one-cell-thick pipes in the middle are the turnaround point.`,
B50: `The liver and bone marrow need whole cells to get in and out of the bloodstream, not just molecules. So their capillaries are the leaky, wide-open kind — more like a chain-link fence than a window screen.`,
B51: `Small pipes have thick muscle for their size, so squeezing them makes a huge difference to flow. They're the faucet handles of your body — tighten them and less gets through to that area.`,
B52: `Veins have one-way flaps so blood can't slide backward, since there's barely any pressure pushing it along. And most of your blood is just sitting in your veins at any moment — they're the storage tank.`,
B53: `Blood from your gut doesn't go straight back to the heart. It takes a detour through the liver first, so the liver can inspect and process everything you just ate before it reaches the rest of you.`,
B54: `By the end of the capillary the pushing pressure has faded, but the proteins left inside are still thirsty and pull water back in. So fluid that leaked out at the start gets sucked back in at the end.`,
B55: `Bulk flow is everything moving together in one shove, like a crowd pushed through a door — not each person choosing their own way. It happens because pressure is higher on one side, and it's what balances how much fluid sits in your blood versus your tissues.`,
B56: `A working muscle makes its own local mess — waste chemicals, less oxygen — and that mess tells nearby pipes to open wider. So the muscle orders its own extra delivery, without anything else changing.`,
B57: `Veins can't push, so they get help: one-way flaps stop backsliding, breathing acts like a bellows, and your leg muscles squeeze the veins as you walk. That's why standing perfectly still makes your legs feel awful and walking fixes it.`,
B58: `Blood this thick is like pumping honey instead of water. Harder to push means more resistance, and more resistance means higher pressure.`,
B59: `Pressure comes down to three things: how much the pump is putting out, how much fluid is in the system, and how tight the pipes are. Change any one and pressure moves.`,
B60: `Some hormones tell your kidneys to hold on to water, which puts more fluid in the pipes and raises pressure. One hormone does the opposite and dumps water. More fluid in a closed system always means more pressure.`,
B61: `You can feel a pulse wherever an artery runs close to the skin over something firm. At your wrist it's the one on the thumb side; behind your knee is a different one further up the leg.`,
B62: `The pump itself broke — a chunk of heart muscle died so it can't squeeze properly. There's plenty of blood, it's just not being moved. Different from shock caused by losing blood.`,
B63: `As you age the big artery near your heart gets stiffer, so it can't cushion each heartbeat, and the top blood-pressure number creeps up. Meanwhile the heart muscle itself gets a bit weaker and can't rev as high.`,
B64: `High blood pressure means the heart is pushing against a heavier door every single beat, all day, for years. Any muscle worked that hard against that much resistance eventually wears out.`,
B65: `Besides trading oxygen for carbon dioxide, your airway helps keep your blood from going too acidic, houses your sense of smell, cleans and warms the air on the way in, and makes your voice.`,
B66: `Split it at the voice box. Nose, sinuses, throat and voice box are the "upper" part. Windpipe, branching tubes and lungs are the "lower" part.`,
B67: `Your throat is a shared hallway — both food and air pass through it, which is exactly why choking is possible. It also shapes your voice and holds the lumpy immune tissue that swells when you're sick.`,
B68: `The lining of your nose runs continuously into your throat, chest, sinuses and even up to your tear ducts. So a germ that starts in your nose can just keep walking down the same hallway.`,
B69: `Your windpipe splits into two branches, and the right one is wider and drops down straighter. So if you inhale a peanut, it usually ends up in the right lung — gravity plus a straighter shot.`,
B70: `The airway branches like an upside-down tree: trunk, big branches, smaller branches, twigs, and finally the leaves — the little grape-cluster sacs where the actual gas swap happens.`,
B71: `The barrier between air and blood is two layers of the flattest cells in your body, pressed together. It's about as thin as a barrier can be, which is the whole point — gas just drifts across on its own.`,
B72: `Lungs get two different blood supplies. One is the blood coming to get oxygenated — that's the cargo. The other is a separate supply that actually feeds the lung's own tissue, because lung tissue needs food too.`,
B73: `Breathing out normally takes no effort. You just stop holding your chest open and everything springs back, squeezing air out — like letting go of a stretched balloon.`,
B74: `Air pressure around you is about 760. When they say "negative 2," they mean 2 less than that — so 758. It's a comparison, not an actual negative amount of pressure.`,
B75: `Tidal volume is just a normal, relaxed breath — what you're doing right now without thinking about it. All the other measurements are about the extra you could force in or out beyond that.`,
B76: `Capacities are just volumes added together. One of them is what's left in your lungs after a normal breath out. The other is the biggest breath you could take starting from that same point.`,
B77: `Air is a mix of gases, and each one contributes its own share of the total push. Like a crowded room where each group makes part of the noise — you can talk about one group's share separately.`,
B78: `Almost all your oxygen rides piggyback on hemoglobin inside the red cells. Only a tiny bit floats freely in the liquid — oxygen doesn't dissolve well, which is exactly why you need the taxi.`,
B79: `Your brainstem sets the basic in-out rhythm automatically, and a spot just above it smooths the rhythm out. Nerves run from there down to your breathing muscles. Stretch sensors in your lungs also report "full" so you switch to breathing out.`,
B80: `Smoking kills the tiny sweeping hairs that carry snot up and out of your lungs. With the escalator broken, coughing is the only way left to clear it — that's the smoker's cough. Quit and the hairs grow back in a few weeks.`,

/* ===================== HISTOLOGY ===================== */
H1: `On a blood slide, the cell you keep running into with a lumpy, multi-part nucleus is the first-responder germ eater. It's the most common white cell by far, so it's the one you'll spot without hunting.`,
H2: `Cytoplasm stuffed with chunky red-orange grains, and a nucleus in two lobes. That's the allergy-and-parasite cell.`,
H3: `Grains so dark purple you can barely see the nucleus underneath. Rare enough that finding one on a slide is a small victory. It's the one that dumps the chemical behind puffiness and itching.`,
H4: `Almost all nucleus with just a thin blue ring of cytoplasm around it — like a fried egg that's nearly all yolk. It's the smallest white cell, and it's the specialist immune type.`,
H5: `The biggest white cell on the slide, with a nucleus curved like a kidney bean and lots of pale cytoplasm and no grains. It's the one that leaves the blood and becomes a big tissue garbage-eater.`,
H6: `The tiny discs everywhere with pale middles are red cells. They're pinched thin in the center like a jelly doughnut, so more light gets through the middle. And they have no nucleus at all — they dumped it to make room for cargo.`,
H7: `Little purple specks way smaller than any white cell, with no nucleus. Those are the leak-plugging chips that broke off a giant cell back in the bone marrow.`,
H8: `A huge cell in bone marrow with a big lumpy nucleus, way bigger than anything in circulating blood. Bits of it break off and become the chips that plug leaks.`,
H9: `Short, branching, striped cells with one nucleus each, joined end-to-end by dark bands. Only heart muscle looks like that. Skeletal muscle is long and unbranched with many nuclei; smooth muscle has no stripes at all.`,
H10: `Loads of mitochondria means loads of little power plants, and power plants need oxygen. So this tissue can't run without a constant oxygen supply — which is exactly why a blocked heart artery does damage so fast.`,
H11: `The innermost lining of the heart chambers is the same slick material that lines every blood vessel, running continuously into them. So blood never touches anything but that one smooth surface anywhere in the whole system.`,
H12: `Two pipes side by side: the one holding its round shape has a thick muscular wall, so it's the artery. The squashed floppy one is the vein — thin wall, nothing to hold it open once the pressure is gone.`,
H13: `A wall that's just one layer of flat cells is a capillary. That's the whole reason it exists — thin enough for food and oxygen to slip across to your cells.`,
H14: `A big pipe near the heart whose wall is full of wavy stretchy sheets instead of muscle. It's built to balloon out with each heartbeat and spring back between beats, which smooths the jolts into steady flow.`,
H15: `Tall cells with tiny sweeping hairs on top, snot-making cells mixed in, and stiff cartilage bracing the wall. That's the windpipe — the hairs sweep mucus up and out, and the cartilage keeps it from collapsing.`,
H16: `A small lung tube with no cartilage but a clear ring of muscle around it. Since muscle can squeeze it shut, this is the tube that narrows in an asthma attack — the big cartilage-braced ones can't.`,
H17: `The air sacs are lined by two kinds of cells. The flat ones make up almost the whole surface — that's where gas crosses. The rounder ones sprinkled among them make the soapy stuff that keeps the sacs from sticking shut.`,
H18: `Oxygen only has to cross two layers of the flattest cells in your body to go from air into blood. Two cells thick, and that's it — which is why it happens fast, with no pumping required.`,
H19: `Two different cartilages doing two different jobs. The throat flap needs to bend and fold over, so it's the springy kind. The windpipe rings need to stay open, so they're the stiff kind.`,
H20: `Between all the air pockets, lung tissue is a springy mesh. That springiness is why you don't have to work to breathe out — the stretched lung just snaps back on its own.`,
};
