/* BIOL 40B — Lecture Exam 2 · FORM A (80 questions)
   Built from the five decks in "exam 2": Blood, heart anatomy, cardiophysiology,
   blood vessels, Respiratory system — weighted by deck size:
     Blood 19 · Heart anatomy 13 · Cardiac physiology 16 · Blood vessels 16 · Respiratory 16

   Every learning objective in objectives_data.js is hit at least once by this form on
   its own, so taking Form A alone still covers the whole objective list.

   Format: one correct answer + four distractors. AUTHORING CONVENTION — the correct
   option is always written first (ans:0) so the bank can be audited at a glance; the
   engine shuffles the five choices on every render, so the student never sees a
   position pattern. `obj` lists the learning-objective ids the item tests. */
const EXAM_A = [

/* ============================ BLOOD · 19 ============================ */
{n:1, topic:"blood", obj:["B1"],
 q:`Which of the following best summarizes the three general functions of blood?`,
 opts:[`Transport of gases, nutrients and wastes; regulation of pH, body temperature and fluid balance; and protection through clotting and immune defense.`,
       `Production of hormones, digestion of nutrients, and storage of calcium.`,
       `Filtration of nitrogenous waste, absorption of water, and synthesis of vitamin D.`,
       `Mechanical support of the organs, storage of calcium, and generation of movement.`,
       `Detection of light and sound, conscious thought, and control of voluntary muscle.`],
 ans:0, why:`Blood transports (gases, nutrients, wastes, hormones), regulates (pH, temperature, fluid balance), and protects (clotting plus immune defense).`},

{n:2, topic:"blood", hy:1, obj:["B2"],
 q:`A tube of blood from a healthy adult is centrifuged. Roughly 45% of the total volume ends up as packed cells at the bottom. What is that 45% value called, and what is the layer above it?`,
 opts:[`The hematocrit, which is almost entirely erythrocytes; above it sits the straw-coloured plasma.`,
       `The leukocyte count; above it sits the buffy coat.`,
       `The plasma fraction; above it sits the serum.`,
       `The platelet fraction; above it sits a layer of fibrin.`,
       `The hemoglobin concentration; above it sits lymph.`],
 ans:0, why:`Hematocrit is the percentage of blood volume made up of packed red cells — normally about 45%. Plasma is the ~55% above it, with the thin buffy coat of WBCs and platelets in between.`},

{n:3, topic:"blood", obj:["B2"],
 q:`Which list places the formed elements in order from most numerous to least numerous in normal adult blood?`,
 opts:[`Erythrocytes → platelets → leukocytes`,
       `Leukocytes → erythrocytes → platelets`,
       `Platelets → erythrocytes → leukocytes`,
       `Erythrocytes → leukocytes → platelets`,
       `Leukocytes → platelets → erythrocytes`],
 ans:0, why:`RBCs run 4.8–5.4 million/µL, platelets 150,000–400,000/µL, and WBCs only 4,500–11,000/µL.`},

{n:4, topic:"blood", hy:1, obj:["B3"],
 q:`Which plasma protein makes up about 60% of all plasma proteins, is the main contributor to blood osmotic pressure, and transports substances such as bilirubin, bile salts and thyroid hormone?`,
 opts:[`Albumin`, `Fibrinogen`, `Gamma globulin`, `Alpha globulin`, `Thromboplastin`],
 ans:0, why:`Albumin is ~60% of plasma protein. It holds water in the bloodstream (osmotic pressure) and acts as a general transport protein.`},

{n:5, topic:"blood", obj:["B3"],
 q:`A patient's lab work shows a selective deficiency of gamma globulins. Based on the functions of the plasma proteins, what is the most likely consequence?`,
 opts:[`Impaired antibody-mediated immune defense, because the gamma globulins are the immunoglobulins.`,
       `An inability to form fibrin, because gamma globulins are the precursor of the clotting protein fibrin.`,
       `A collapse in blood osmotic pressure, because gamma globulins account for 60% of plasma protein.`,
       `Failure to transport iron and cholesterol, which is the specific job of the gamma globulins.`,
       `Loss of the plasma's ability to carry dissolved oxygen directly.`],
 ans:0, why:`Gamma globulins are the antibodies (immunoglobulins). Fibrinogen is the fibrin precursor, albumin handles osmotic pressure, and the alpha/beta globulins transport hormones, cholesterol and iron.`},

{n:6, topic:"blood", hy:1, obj:["B4"],
 q:`Three features make the erythrocyte efficient at gas transport. Which statement correctly pairs a feature with its advantage?`,
 opts:[`It has no mitochondria, so it makes ATP anaerobically and does not consume the oxygen it is carrying.`,
       `It has a large nucleus, which lets it divide and replace itself while in circulation.`,
       `Its spherical shape minimizes surface area, protecting the hemoglobin from oxidation.`,
       `It is packed with mitochondria, giving it the aerobic ATP needed to pump oxygen into the tissues.`,
       `Hemoglobin makes up only about 3% of the cell volume, which keeps the cell flexible.`],
 ans:0, why:`The three features: a biconcave shape (huge surface area per volume), hemoglobin at ~97% of cell volume, and no mitochondria — so RBCs never burn the O₂ they haul.`},

{n:7, topic:"blood", obj:["B4"],
 q:`How many oxygen molecules can a single hemoglobin molecule carry, and what part of the molecule actually binds each one?`,
 opts:[`Four — the central iron atom of each of the four heme groups.`,
       `One — the central iron atom of a single heme group.`,
       `Four — the globin polypeptide chains themselves.`,
       `Two — the magnesium ion at the centre of each heme group.`,
       `Two hundred fifty million — the enzyme carbonic anhydrase.`],
 ans:0, why:`Hemoglobin is 4 globin chains, each carrying a heme whose central iron binds one O₂ — 4 O₂ per Hb. Each RBC holds about 250 million Hb molecules.`},

{n:8, topic:"blood", hy:1, obj:["B4"],
 q:`A patient with chronic kidney disease becomes anemic. What is the mechanism, and where would the missing signal normally act?`,
 opts:[`The kidneys produce less erythropoietin, so the red bone marrow is never told to step up erythropoiesis.`,
       `The kidneys stop producing hemoglobin, so the red cells that are made cannot carry oxygen.`,
       `The liver stops destroying worn-out erythrocytes, so young cells are crowded out of the marrow.`,
       `The kidneys fail to absorb dietary iron from the small intestine.`,
       `The spleen produces less intrinsic factor, so vitamin B₁₂ cannot be absorbed.`],
 ans:0, why:`The kidneys release EPO in response to low blood oxygen, and EPO drives erythropoiesis in red bone marrow. Renal disease → too little EPO → renal anemia, treated with synthetic EPO.`},

{n:9, topic:"blood", obj:["B5"],
 q:`An autoimmune process destroys the stomach mucosa cells that make intrinsic factor. What anemia results, and what do the erythrocytes look like?`,
 opts:[`Pernicious anemia; without B₁₂ the developing RBCs enlarge into macrocytes but cannot divide.`,
       `Iron-deficiency anemia; the RBCs are small, pale microcytes.`,
       `Aplastic anemia; every formed-element cell line is missing.`,
       `Sickle-cell anemia; the RBCs become crescent-shaped when oxygen is low.`,
       `Renal anemia; RBC numbers are low but the cells themselves are normal.`],
 ans:0, why:`Intrinsic factor is required to absorb vitamin B₁₂, and B₁₂ is required for the DNA synthesis of rapidly dividing cells. No B₁₂ → large macrocytes. Treated with B₁₂ injections or nasal gel.`},

{n:10, topic:"blood", hy:1, obj:["B5"],
 q:`In sickle-cell anemia a single amino acid is wrong in a 146-amino-acid beta globin chain. When do the erythrocytes actually deform, and why is that dangerous?`,
 opts:[`When oxygen levels fall — during exercise, for example; the crescent-shaped cells rupture easily and block small vessels.`,
       `Only when oxygen levels are high, as in the pulmonary capillaries; the cells then bind too much oxygen.`,
       `Continuously from birth regardless of oxygen level; the cells cannot bind iron at all.`,
       `Only after the spleen has been removed; the cells then lose their biconcave shape.`,
       `When blood pH rises above normal; the cells swell and lyse inside the marrow.`],
 ans:0, why:`Hemoglobin S distorts the cell when O₂ is low. The misshapen cells rupture and jam small vessels, causing pain and poor oxygen delivery.`},

{n:11, topic:"blood", obj:["B5"],
 q:`A patient's hematocrit comes back at 70%. Which condition does that suggest, and what is the main hemodynamic consequence?`,
 opts:[`Polycythemia; the excess RBCs raise blood viscosity and make blood flow sluggish.`,
       `Leukopenia; the low WBC count thins the blood and speeds flow.`,
       `Thrombocytopenia; the missing platelets allow spontaneous widespread hemorrhage.`,
       `Iron-deficiency anemia; the small pale microcytes lower viscosity and speed flow.`,
       `Aplastic anemia; the marrow has been destroyed, so viscosity falls.`],
 ans:0, why:`Polycythemia is an abnormal excess of RBCs. In polycythemia vera (a bone marrow cancer) hematocrit can reach 80%; treatment is therapeutic phlebotomy. Secondary polycythemia follows low O₂, as at high altitude.`},

{n:12, topic:"blood", hy:1, obj:["B6"],
 q:`Using the mnemonic "Never let monkeys eat bananas," which leukocyte is most abundant in normal blood, and roughly what share of the total does it make up?`,
 opts:[`Neutrophil — 60–70%`, `Lymphocyte — 60–70%`, `Monocyte — 25–33%`, `Eosinophil — 10–15%`, `Basophil — just under 50%`],
 ans:0, why:`Neutrophils, lymphocytes, monocytes, eosinophils, basophils — in decreasing abundance. Neutrophils are 60–70%; basophils are under 1%.`},

{n:13, topic:"blood", obj:["B6"],
 q:`A patient has a heavy parasitic infection along with a strong allergic reaction. Which granulocyte would you expect to be elevated, and which granulocyte releases the histamine behind the allergic symptoms?`,
 opts:[`Eosinophils elevated; basophils release the histamine.`,
       `Basophils elevated; eosinophils release the histamine.`,
       `Neutrophils elevated; monocytes release the histamine.`,
       `Lymphocytes elevated; neutrophils release the histamine.`,
       `Monocytes elevated; lymphocytes release the histamine.`],
 ans:0, why:`Eosinophils are the allergy/parasite granulocyte; basophils contain and release histamine. Neutrophils are the first-responder phagocytes that trigger inflammation.`},

{n:14, topic:"blood", hy:1, obj:["B7"],
 q:`What exactly is a platelet, and where does it come from?`,
 opts:[`An irregularly shaped cell fragment shed from a megakaryocyte.`,
       `A small nucleated cell manufactured by the spleen.`,
       `A biconcave anucleate cell that matures from a reticulocyte.`,
       `An agranular leukocyte that migrates into tissue and becomes a macrophage.`,
       `A plasma protein that polymerizes into fibrin threads.`],
 ans:0, why:`Platelets (thrombocytes) are cell fragments from megakaryocytes, 150,000–400,000/µL, and they are central to clotting.`},

{n:15, topic:"blood", obj:["B7"],
 q:`Why do platelets not stick to the wall of an undamaged blood vessel?`,
 opts:[`Collagen is not exposed, and the endothelial cells release prostacyclin and nitric oxide, which inhibit platelet aggregation.`,
       `Intact endothelium carries a positive charge that repels platelets.`,
       `Circulating thrombin continuously digests any platelet that touches the wall.`,
       `Platelets have no collagen receptors until the spleen activates them.`,
       `Intact vessels contain no calcium, and platelets need calcium to move.`],
 ans:0, why:`Platelets stick to collagen fibers, which are only exposed once the vessel is damaged. Healthy endothelium also actively secretes prostacyclin and NO to keep platelets from aggregating.`},

{n:16, topic:"blood", hy:1, obj:["B8"],
 q:`Hemostasis proceeds through three phases. Which order is correct?`,
 opts:[`Vascular spasm → platelet plug formation → coagulation`,
       `Coagulation → vascular spasm → platelet plug formation`,
       `Platelet plug formation → coagulation → vascular spasm`,
       `Fibrinolysis → vascular spasm → clot retraction`,
       `Clot retraction → coagulation → platelet plug formation`],
 ans:0, why:`Hemostasis prevents blood loss from a damaged vessel: the vessel constricts, platelets plug the gap, then the clotting cascade lays down fibrin. All three overlap in time.`},

{n:17, topic:"blood", hy:1, obj:["B8"],
 q:`In the final common pathway of the clotting cascade, what is the specific action of thrombin?`,
 opts:[`It converts fibrinogen into fibrin.`,
       `It converts fibrin into fibrinogen.`,
       `It converts plasminogen into plasmin.`,
       `It converts prothrombin into thromboplastin.`,
       `It converts hemoglobin into bilirubin.`],
 ans:0, why:`Thrombin converts fibrinogen → fibrin, activates stabilizing factor XIII, promotes more thrombin from prothrombin, and enhances platelet aggregation. The whole cascade needs Ca²⁺.`},

{n:18, topic:"blood", obj:["B9"],
 q:`A clot forms and stays put inside an unbroken vessel; a fragment then breaks loose, travels in the bloodstream, and lodges in a pulmonary vessel. Name these three things in order.`,
 opts:[`Thrombus, embolus, embolism`,
       `Embolus, thrombus, infarction`,
       `Petechia, thrombus, embolism`,
       `Thrombus, infarct, aneurysm`,
       `Embolism, embolus, thrombus`],
 ans:0, why:`A thrombus persists in an unbroken vessel; a freely floating thrombus is an embolus; an embolus that obstructs a vessel is an embolism. Risk factors include atherosclerosis, inflammation and blood stasis from immobility.`},

{n:19, topic:"blood", obj:["B10"],
 q:`A patient with type A blood is transfused with type B blood. Why can the reaction be fatal?`,
 opts:[`Type A plasma carries anti-B antibodies, which agglutinate the donated type B cells.`,
       `Type A plasma carries anti-A antibodies, which agglutinate the recipient's own cells.`,
       `Type B cells carry no surface antigens, so they go unrecognized and are stored in the spleen.`,
       `Type B blood contains no plasma proteins, so the recipient's osmotic pressure collapses.`,
       `Type A and type B cells fuse into type AB cells, which cannot carry oxygen.`],
 ans:0, why:`In the ABO system you carry antibodies against the antigen you lack. Type A plasma has anti-B, so donated B cells are agglutinated — which is why blood typing is done before any transfusion.`},

/* ======================= HEART ANATOMY · 13 ======================= */
{n:20, topic:"heart", obj:["H1"],
 q:`Where is the heart located, and how is it oriented in the thorax?`,
 opts:[`In the mediastinum between the second rib and the fifth intercostal space, with the base leaning toward the right shoulder and the apex pointing toward the left hip.`,
       `In the mediastinum, with the apex leaning toward the right shoulder and the base pointing toward the left hip.`,
       `In the pleural cavity of the left lung, with the base resting on the diaphragm.`,
       `Posterior to the vertebral column and anterior to the sternum, entirely above the second rib.`,
       `In the pericardial cavity just inferior to the diaphragm, with the apex pointing superiorly.`],
 ans:0, why:`Fist-sized, under 1 pound, sitting on the diaphragm, posterior to the sternum and anterior to the vertebral column. The apical pulse is palpated between the fifth and sixth ribs, just below the left nipple.`},

{n:21, topic:"heart", hy:1, obj:["H1"],
 q:`Which sequence moves correctly from the outermost covering of the heart inward to the heart muscle?`,
 opts:[`Fibrous pericardium → parietal layer of serous pericardium → pericardial cavity → visceral layer (epicardium) → myocardium`,
       `Visceral pericardium → pericardial cavity → fibrous pericardium → endocardium → myocardium`,
       `Endocardium → myocardium → epicardium → parietal pericardium → fibrous pericardium`,
       `Fibrous pericardium → myocardium → pericardial cavity → endocardium → epicardium`,
       `Parietal pericardium → endocardium → pericardial cavity → myocardium → epicardium`],
 ans:0, why:`The tough fibrous pericardium protects and anchors the heart and prevents overfilling. Inside it, the two serous layers are separated by fluid in the pericardial cavity, which cuts friction. The visceral layer IS the epicardium.`},

{n:22, topic:"heart", obj:["H1"],
 q:`Excess fluid is leaking into a patient's pericardial space and compressing the heart, limiting its ability to pump. What is this, and how is it treated?`,
 opts:[`Cardiac tamponade; the fluid is drawn out of the cavity by pericardiocentesis.`,
       `Pericarditis; the pericardium is surgically fused to the myocardium.`,
       `Valvular stenosis; the stiffened valve is replaced with a mechanical valve.`,
       `Myocardial infarction; the blocked coronary artery is stented open.`,
       `Angina pectoris; the patient is given a drug to dilate the coronary vessels.`],
 ans:0, why:`Pericarditis is inflammation that roughens the membranes and produces a creaking pericardial friction rub. Cardiac tamponade is fluid in the pericardial space squeezing the heart — drained by pericardiocentesis.`},

{n:23, topic:"heart", obj:["H1"],
 q:`Which statement about the atria is correct?`,
 opts:[`They are small, thin-walled receiving chambers; their auricles increase atrial volume, and pectinate muscles are found in the auricles.`,
       `They are the thick-walled discharging chambers that generate most of the heart's pumping force.`,
       `They are separated from one another by the interventricular septum.`,
       `Their inner walls carry trabeculae carneae and papillary muscles that anchor the chordae tendineae.`,
       `The right atrium receives oxygenated blood returning through four pulmonary veins.`],
 ans:0, why:`Atria receive blood from veins and contribute little propulsion. They are divided by the interatrial septum. Trabeculae carneae and papillary muscles belong to the ventricles.`},

{n:24, topic:"heart", obj:["H1"],
 q:`What keeps the cusps of the atrioventricular valves from being everted back into the atria when ventricular pressure rises?`,
 opts:[`Chordae tendineae anchoring the cusps to the papillary muscles.`,
       `Trabeculae carneae bracing the cusps against the interventricular septum.`,
       `The three semilunar cusps attaching to the artery wall.`,
       `Pectinate muscles contracting inside the auricles.`,
       `The fibrous pericardium preventing overfilling of the chambers.`],
 ans:0, why:`Chordae tendineae run from the AV valve cusps to papillary muscles projecting off the ventricular wall. They hold the flaps closed and stop them from flipping backward.`},

{n:25, topic:"heart", hy:1, obj:["H2"],
 q:`Which three vessels empty into the right atrium?`,
 opts:[`Superior vena cava, inferior vena cava, and coronary sinus`,
       `Superior vena cava, inferior vena cava, and pulmonary trunk`,
       `The four pulmonary veins and the coronary sinus`,
       `Aorta, pulmonary trunk, and coronary sinus`,
       `Right and left pulmonary arteries and the superior vena cava`],
 ans:0, why:`SVC drains everything above the diaphragm, IVC everything below it, and the coronary sinus drains the coronary veins of the heart wall itself.`},

{n:26, topic:"heart", hy:1, obj:["H2"],
 q:`Trace a drop of deoxygenated blood arriving in the right atrium. Which pathway is correct?`,
 opts:[`Right atrium → tricuspid valve → right ventricle → pulmonary valve → pulmonary trunk → lungs → pulmonary veins → left atrium → bicuspid valve → left ventricle → aortic valve → aorta`,
       `Right atrium → bicuspid valve → right ventricle → aortic valve → aorta → lungs → pulmonary arteries → left atrium`,
       `Right atrium → right ventricle → pulmonary veins → lungs → pulmonary arteries → left atrium → left ventricle → aorta`,
       `Left atrium → tricuspid valve → left ventricle → pulmonary trunk → lungs → vena cava → right atrium`,
       `Right atrium → tricuspid valve → left ventricle → pulmonary valve → aorta → lungs → left atrium`],
 ans:0, why:`Arteries always carry blood away from the heart and veins return it — which is why the pulmonary ARTERIES carry deoxygenated blood and the pulmonary VEINS carry oxygenated blood.`},

{n:27, topic:"heart", obj:["H2"],
 q:`Which statement about coronary circulation is correct?`,
 opts:[`The left and right coronary arteries arise from the base of the aorta, and the myocardium is perfused mainly while the heart is relaxed.`,
       `The coronary arteries branch from the pulmonary trunk and fill during ventricular systole.`,
       `The coronary sinus delivers oxygenated blood to the myocardium during diastole.`,
       `Coronary blood comes from the bronchial arteries off the aortic arch.`,
       `The right ventricle receives most of the coronary supply because it is the thickest chamber.`],
 ans:0, why:`Coronary circulation is the shortest circuit in the body. Both coronary arteries leave the base of the aorta and encircle the heart in the coronary sulcus; delivery happens during relaxation, and the left ventricle takes most of it.`},

{n:28, topic:"heart", obj:["H2","C10"],
 q:`One patient reports fleeting chest pain on exertion that fades with rest. A second has a prolonged coronary blockage. What distinguishes the outcomes?`,
 opts:[`The first has angina pectoris and the cells are only weakened; the second has a myocardial infarction, and the dead tissue is replaced by noncontractile scar.`,
       `The first has a myocardial infarction with permanent cell death; the second has angina with fully reversible injury.`,
       `Both kill myocardial cells, but only angina leaves scar tissue behind.`,
       `The first is caused by pericardial inflammation; the second by an incompetent valve.`,
       `Neither involves the coronary arteries; both result from valvular stenosis.`],
 ans:0, why:`Angina pectoris is thoracic pain from a fleeting deficiency in blood delivery to the myocardium — cells are weakened, not killed. A prolonged blockage kills myocardium, and the dead area heals as noncontractile scar.`},

{n:29, topic:"heart", hy:1, obj:["H3"],
 q:`Which structure initiates and regulates the heartbeat, where is it, and at what intrinsic rate does it fire?`,
 opts:[`The sinoatrial node, in the upper portion of the right atrium, at 60–100 impulses per minute.`,
       `The atrioventricular node, at the junction of the right atrium and right ventricle, at 60–100 impulses per minute.`,
       `The bundle of His, in the interventricular septum, at 100–120 impulses per minute.`,
       `The Purkinje fibers, in the ventricular walls, at 60–100 impulses per minute.`,
       `The cardiovascular center of the medulla oblongata, at 70 impulses per minute.`],
 ans:0, why:`The SA node is modified myocardial tissue that fires without any external nerve stimulus — the pacemaker, at 60–100/min. The AV node runs 40–60, bundle branches ~40, Purkinje fibers ~20.`},

{n:30, topic:"heart", obj:["H3"],
 q:`The AV node delays the impulse by about 0.1 second. What does that delay accomplish?`,
 opts:[`It lets the atria finish contracting so the ventricles are fully filled before they contract.`,
       `It lets the ventricles contract before the atria, emptying the heart more completely.`,
       `It stops the SA node from firing more than once per cardiac cycle.`,
       `It gives the semilunar valves time to close before the AV valves open.`,
       `It lets the Purkinje fibers repolarize before the atria depolarize.`],
 ans:0, why:`Atrial excitation and contraction must finish before ventricular contraction starts. The AV delay is what buys that time — complete atrial contraction and ventricular filling.`},

{n:31, topic:"heart", hy:1, obj:["H3"],
 q:`Which sequence correctly traces the impulse through the conduction system?`,
 opts:[`SA node → AV node → AV bundle (bundle of His) → bundle branches → Purkinje fibers`,
       `AV node → SA node → Purkinje fibers → bundle branches → bundle of His`,
       `SA node → Purkinje fibers → AV node → bundle branches → bundle of His`,
       `SA node → bundle branches → AV node → bundle of His → Purkinje fibers`,
       `AV node → bundle of His → SA node → Purkinje fibers → bundle branches`],
 ans:0, why:`The bundle of His splits into right and left bundle branches in the interventricular septum, which hand off to Purkinje fibers that spread the impulse evenly through both ventricles from the apex up.`},

{n:32, topic:"heart", obj:["H4","C1"],
 q:`Which combination of features is characteristic of cardiac muscle tissue?`,
 opts:[`Striated, short, branched cells joined by intercalated discs containing gap junctions, so the myocardium contracts as a functional syncytium, and it depends almost entirely on aerobic respiration.`,
       `Long, unbranched, multinucleate fibers joined by tendons, contracting only when a somatic motor neuron fires.`,
       `Nonstriated spindle-shaped cells with no gap junctions, contracting slowly and independently of one another.`,
       `Striated branched cells with no gap junctions, so each cell must be stimulated individually by the SA node.`,
       `Branched cells with very few mitochondria, letting the heart work anaerobically for long stretches.`],
 ans:0, why:`Intercalated discs anchor the cells and let ions pass through gap junctions, so all cardiomyocytes contract as a unit — or none do. Cardiac muscle has more mitochondria than skeletal muscle and cannot function without oxygen.`},

/* ==================== CARDIAC PHYSIOLOGY · 16 ==================== */
{n:33, topic:"cardio", obj:["C1"],
 q:`About 1% of cardiac muscle cells are autorhythmic. What gives them the ability to fire spontaneously?`,
 opts:[`An unstable pacemaker potential — slow Na⁺ entry drifts the membrane toward threshold, and then Ca²⁺ influx produces the depolarization.`,
       `A stable resting potential that is depolarized only when a somatic motor neuron releases acetylcholine.`,
       `Continuous K⁺ influx that pushes the membrane to threshold.`,
       `Cl⁻ influx for depolarization and Na⁺ efflux for repolarization.`,
       `Sympathetic stimulation, without which the heart cannot beat at all.`],
 ans:0, why:`Autorhythmic cells have no stable resting potential. Their membrane drifts to threshold on slow Na⁺ entry, Ca²⁺ influx (not Na⁺) drives the depolarizing phase, and K⁺ efflux repolarizes them.`},

{n:34, topic:"cardio", obj:["C2"],
 q:`What produces the plateau phase of the action potential in a cardiac contractile fiber?`,
 opts:[`Ca²⁺ entering through slow calcium channels, which prolongs depolarization and delays repolarization.`,
       `K⁺ entering through leak channels, which holds the membrane at threshold.`,
       `Na⁺ continuing to enter through fast voltage-gated sodium channels that never inactivate.`,
       `Cl⁻ entering the cell, hyperpolarizing the membrane for about 200 ms.`,
       `The Na⁺/K⁺ pump reversing and pumping Na⁺ inward.`],
 ans:0, why:`Sequence in a contractile cell: a depolarizing wave arrives through gap junctions → fast Na⁺ channels open → Na⁺ channels close and slow Ca²⁺ channels open, giving the plateau → Ca²⁺ channels close, K⁺ channels open, repolarization.`},

{n:35, topic:"cardio", obj:["C2"],
 q:`Cardiac muscle has a long absolute refractory period. Functionally, why does that matter?`,
 opts:[`It prevents summation and tetanus, so the chambers have time to refill between beats.`,
       `It permits summation, so the heart can build progressively stronger contractions.`,
       `It makes the atria and ventricles contract at the same instant.`,
       `It lets the heart contract without any calcium entering the cell.`,
       `It stops an ectopic focus from ever overriding the SA node.`],
 ans:0, why:`A heart that could go into tetanus would never refill. The long absolute refractory period is what guarantees relaxation and filling between contractions.`},

{n:36, topic:"cardio", hy:1, obj:["C3"],
 q:`On a normal ECG, what does the P wave represent?`,
 opts:[`Depolarization of all the cells of the atria except the SA node — normally an upward deflection.`,
       `Repolarization of the atria — normally a downward deflection.`,
       `Depolarization of the ventricles, recorded as three separate waves.`,
       `Repolarization of the ventricles — normally an upward deflection.`,
       `The plateau phase of the ventricular action potential, recorded as a flat line.`],
 ans:0, why:`The small initial P wave is atrial depolarization and nearly always registers upward. Note that an ECG records changes in electrical activity relative to the electrodes — it does not measure the value of any action potential.`},

{n:37, topic:"cardio", hy:1, obj:["C3"],
 q:`Which pairing of ECG waveform and electrical event is correct?`,
 opts:[`QRS complex = ventricular depolarization; T wave = ventricular repolarization`,
       `QRS complex = ventricular repolarization; T wave = ventricular depolarization`,
       `QRS complex = atrial depolarization; T wave = atrial repolarization`,
       `QRS complex = atrial contraction; T wave = ventricular contraction`,
       `QRS complex = the AV nodal delay; T wave = SA node firing`],
 ans:0, why:`The large QRS complex (Q down, R up, S down) is ventricular depolarization; the small T wave that follows is ventricular repolarization and is normally an upward deflection.`},

{n:38, topic:"cardio", obj:["C3"],
 q:`A patient's ECG shows an elevated S-T segment. Why is that segment normally flat, and what does elevation most notably suggest?`,
 opts:[`It is recorded during the ventricular plateau phase, when there is no net change in electrical activity; elevation points to myocardial ischemia, injury or infarction.`,
       `It is recorded while the SA node fires, so elevation means the SA node has been destroyed.`,
       `It is flat simply because it contains no wave components, so elevation only means the heart rate is fast.`,
       `It is recorded during atrial repolarization, so elevation indicates atrial fibrillation.`,
       `It is flat during the AV nodal delay, so elevation indicates a first-degree heart block.`],
 ans:0, why:`The S-T segment is flat because the ventricles are in the plateau phase. Elevation or depression is classically associated with myocardial ischemia, injury and infarction. (Segments contain no wave components; intervals include at least one.)`},

{n:39, topic:"cardio", hy:1, obj:["C4"],
 q:`During mid-to-late diastole — ventricular filling — what is the state of the heart valves?`,
 opts:[`AV valves open, semilunar valves closed`,
       `AV valves closed, semilunar valves open`,
       `Both sets of valves open`,
       `Both sets of valves closed`,
       `Semilunar valves open, then closing as the atria contract`],
 ans:0, why:`Blood flows passively from atria into ventricles through the open AV valves, and atrial systole tops the ventricles off at the end of the phase. The semilunar valves stay shut until ventricular pressure exceeds arterial pressure.`},

{n:40, topic:"cardio", obj:["C4","C5"],
 q:`Ventricular systole begins: rising ventricular pressure has closed the AV valves, but the semilunar valves have not opened yet. What is this phase called, and what is happening to ventricular volume?`,
 opts:[`Isovolumetric contraction; volume does not change, because all four valves are closed.`,
       `Ventricular ejection; volume falls rapidly as blood leaves the heart.`,
       `Isovolumetric relaxation; volume is unchanged while the ventricles relax.`,
       `Atrial systole; volume rises as the atria top off the ventricles.`,
       `Ventricular filling; volume rises as blood flows passively from the atria.`],
 ans:0, why:`"Isovolumetric" = same volume. The ventricle is contracting hard with every valve shut, so pressure climbs but no blood moves — until pressure exceeds aortic/pulmonary pressure and the semilunar valves pop open for the ejection phase.`},

{n:41, topic:"cardio", hy:1, obj:["C5"],
 q:`What produces the first and second heart sounds — the "lub-dup"?`,
 opts:[`The first is the AV valves closing at the start of ventricular systole; the second is the semilunar valves closing at the start of ventricular diastole.`,
       `The first is the semilunar valves closing at the start of systole; the second is the AV valves closing at the start of diastole.`,
       `The first is the AV valves opening; the second is the semilunar valves opening.`,
       `Both sounds come from turbulent flow through the coronary arteries.`,
       `The first is atrial contraction; the second is ventricular contraction.`],
 ans:0, why:`Heart sounds come from valves closing, not opening. S1 (AV valves) marks the beginning of systole; S2 (semilunar valves) marks the beginning of ventricular diastole.`},

{n:42, topic:"cardio", obj:["C5"],
 q:`In early diastole the ventricles relax and ventricular pressure drops below aortic pressure. What happens next?`,
 opts:[`Backflow of blood in the aorta and pulmonary trunk snaps the semilunar valves shut, and the ventricles keep relaxing without a change in volume until the AV valves open.`,
       `The pressure drop holds the semilunar valves open, letting blood re-enter the ventricles from the aorta.`,
       `The AV valves close and the atria contract against closed valves.`,
       `Ventricular pressure rises sharply and the semilunar valves reopen for a second ejection.`,
       `The papillary muscles contract to force the semilunar valves open.`],
 ans:0, why:`That is isovolumetric relaxation. While it happens the atria are refilling; when atrial pressure exceeds ventricular pressure the AV valves open and the cycle repeats.`},

{n:43, topic:"cardio", obj:["C6"],
 q:`A drug is described as having a positive chronotropic effect. What does it do, and which physiological factor works the same way?`,
 opts:[`It increases heart rate — as sympathetic stimulation with norepinephrine does.`,
       `It decreases heart rate — as sympathetic stimulation with norepinephrine does.`,
       `It raises stroke volume only, leaving heart rate untouched — as thyroxine does.`,
       `It lowers contractility only — as epinephrine does.`,
       `It increases heart rate — as parasympathetic stimulation with acetylcholine does.`],
 ans:0, why:`Chronotropic agents affect heart rate: positive ones speed it up, negative ones slow it down. Sympathetic NE/E opens more Na⁺ and Ca²⁺ channels and speeds depolarization; parasympathetic ACh raises K⁺ permeability and hyperpolarizes, slowing the rate.`},

{n:44, topic:"cardio", hy:1, obj:["C7"],
 q:`Cardiac output is the volume of blood pumped by each ventricle per minute. If heart rate is 75 beats/min and stroke volume is 70 mL/beat, what is the cardiac output?`,
 opts:[`5,250 mL/min — about 5.25 L/min`, `145 mL/min`, `1,050 mL/min`, `52,500 mL/min — about 52.5 L/min`, `1.07 mL/min`],
 ans:0, why:`CO = HR × SV = 75 × 70 = 5,250 mL/min. Cardiac reserve is the difference between resting and maximal CO — 20–25 L/min in most people, up to about 40 L/min in athletes.`},

{n:45, topic:"cardio", hy:1, obj:["C8"],
 q:`An athlete's stroke volume climbs during exercise largely because more blood returns to the heart between beats. Which factor is that, and how does it raise stroke volume?`,
 opts:[`Preload — greater venous return stretches the ventricle and raises end-diastolic volume, so more blood is ejected.`,
       `Afterload — the higher arterial pressure the ventricle must overcome, which increases the volume ejected.`,
       `Contractility — the force of contraction at a given fiber length, which is set by the SA node's firing rate.`,
       `Chronotropy — a rise in heart rate, which by definition raises stroke volume.`,
       `Cardiac reserve — the gap between resting and maximal cardiac output, which is another name for stroke volume.`],
 ans:0, why:`The three stroke-volume factors are preload (degree of stretch/EDV, set mostly by venous return), contractility (force at a given fiber length, boosted by NE/E and Ca²⁺), and afterload (the pressure that must be overcome to eject).`},

{n:46, topic:"cardio", obj:["C8"],
 q:`A patient with long-standing hypertension has a chronically elevated afterload. What is afterload, and what does raising it do to stroke volume?`,
 opts:[`It is the pressure the ventricle must exceed to open the semilunar valves; a higher afterload lowers stroke volume.`,
       `It is the degree of ventricular stretch before contraction; a higher afterload raises stroke volume.`,
       `It is the volume in the ventricle at the end of diastole; a higher afterload raises stroke volume.`,
       `It is the force of contraction independent of fiber length; afterload has no effect on stroke volume.`,
       `It is the blood left in the ventricle after ejection; a higher afterload eliminates that residual volume.`],
 ans:0, why:`Afterload is the back-pressure the ventricle works against. With hypertension the ventricle spends more of its effort just getting the semilunar valve open, so less blood is ejected per beat.`},

{n:47, topic:"cardio", hy:1, obj:["C9"],
 q:`Which change would be expected to DECREASE heart rate?`,
 opts:[`Elevated extracellular K⁺`, `Elevated extracellular Ca²⁺`, `Release of epinephrine and thyroxine`, `A rise in body temperature`, `Exercise`],
 ans:0, why:`Elevated K⁺ and Na⁺ in the ECF decrease heart rate; elevated Ca²⁺ increases it. Epinephrine and thyroxine, higher temperature and exercise all raise HR; increasing age lowers it.`},

{n:48, topic:"cardio", obj:["C10"],
 q:`A patient's AV node is damaged. Based on the intrinsic rates of the conduction system, what happens?`,
 opts:[`A heart block develops, and the ventricles contract at roughly 30 beats per minute.`,
       `The heart stops entirely, because the AV node is the pacemaker.`,
       `Heart rate climbs above 100 beats per minute, producing tachycardia.`,
       `The atria drop to about 30 beats per minute while the ventricles stay near 75.`,
       `Fibrillation develops, with the whole myocardium twitching at about 250 beats per minute.`],
 ans:0, why:`Damage to the SA node hands pacing to the AV node at ~50 bpm. Damage to the AV node is heart block, and the ventricles fall back on their own slow rhythm, ~30 bpm. Bradycardia is <60, tachycardia >100, and fibrillation is chaotic, uncoordinated twitching.`},

/* ======================= BLOOD VESSELS · 16 ======================= */
{n:49, topic:"vessels", obj:["V1","V3"],
 q:`Which sequence describes the vessels blood passes through travelling from the heart out to a tissue and back?`,
 opts:[`Artery → arteriole → capillary → venule → vein`,
       `Vein → venule → capillary → arteriole → artery`,
       `Artery → capillary → arteriole → vein → venule`,
       `Arteriole → artery → capillary → vein → venule`,
       `Artery → venule → capillary → arteriole → vein`],
 ans:0, why:`Arteries branch into arterioles, which feed the capillary networks where exchange happens. Capillaries merge into venules, and venules unite into veins that return blood to the heart.`},

{n:50, topic:"vessels", hy:1, obj:["V2"],
 q:`Which layer of a blood vessel wall holds the smooth muscle and elastic fibers that let the vessel change diameter?`,
 opts:[`Tunica media`, `Tunica interna (intima)`, `Tunica externa`, `The basement membrane`, `The endothelium lining the lumen`],
 ans:0, why:`Three layers: tunica interna lines the lumen, tunica media is the smooth muscle and elastic fiber layer, tunica externa is the outer connective tissue. Smooth muscle in the media is why arteries can regulate their diameter.`},

{n:51, topic:"vessels", hy:1, obj:["V2"],
 q:`What structural feature makes capillaries the only vessels where exchange between blood and tissue cells can happen?`,
 opts:[`Their walls are a single layer of endothelial cells on a basement membrane.`,
       `Their tunica media is unusually thick and muscular.`,
       `They contain one-way valves that trap fluid out in the tissue.`,
       `Their tunica externa is thicker than that of any other vessel.`,
       `They are the widest vessels in the body, so flow through them is fastest.`],
 ans:0, why:`Capillaries are microscopic vessels connecting arterioles to venules, and their walls are one cell thick — thin enough for nutrients and wastes to cross between blood and tissue.`},

{n:52, topic:"vessels", hy:1, obj:["V2"],
 q:`Compared with arteries, veins have…`,
 opts:[`a thinner tunica interna and media, a thicker tunica externa, less elastic tissue and smooth muscle, and valves.`,
       `a thicker tunica media with more elastic tissue, and no valves.`,
       `identical wall structure, differing only in the direction blood flows.`,
       `a single-cell-thick wall and no tunica externa at all.`,
       `more smooth muscle than arteries, which is what drives venous return.`],
 ans:0, why:`Veins are low-pressure vessels: thinner media, thicker externa, and valves to stop backflow. At rest the largest share of blood sits in the systemic veins and venules — the "blood reservoirs."`},

{n:53, topic:"vessels", obj:["V3","V2"],
 q:`Blood leaves the left ventricle. Which statement correctly describes the two types of arteries it travels through?`,
 opts:[`Elastic (conducting) arteries such as the aorta act as pressure reservoirs; muscular (distributing) arteries then deliver blood to particular body regions.`,
       `Muscular arteries act as the pressure reservoirs; elastic arteries distribute blood to particular regions.`,
       `Both types are passive conduits, since neither contains smooth muscle.`,
       `Elastic arteries are the smallest vessels and empty directly into capillary beds.`,
       `Muscular arteries contain more elastic fibers and less smooth muscle than elastic arteries.`],
 ans:0, why:`Elastic arteries are large with lots of elastic fiber; they absorb the pressure surge of ventricular ejection and act as pressure reservoirs. Muscular arteries are medium-sized with more smooth muscle, and they distribute blood.`},

{n:54, topic:"vessels", hy:1, obj:["V4"],
 q:`At the arterial end of a capillary bed, which pressure relationship drives fluid OUT of the capillary and into the interstitial space?`,
 opts:[`Blood hydrostatic pressure exceeds blood colloid osmotic pressure, so net filtration occurs.`,
       `Blood colloid osmotic pressure exceeds blood hydrostatic pressure, so net filtration occurs.`,
       `Interstitial hydrostatic pressure exceeds blood hydrostatic pressure, so net filtration occurs.`,
       `The two pressures are equal, and fluid is pushed out by active transport.`,
       `Plasma proteins leave the capillary first and drag fluid after them by transcytosis.`],
 ans:0, why:`Bulk flow moves fluid from higher to lower pressure. At the arterial end hydrostatic (pushing-out) pressure wins and fluid filters out; at the venous end colloid osmotic (pulling-in) pressure from plasma proteins wins and fluid is reabsorbed.`},

{n:55, topic:"vessels", obj:["V4"],
 q:`Insulin is a large, lipid-insoluble molecule. How does it cross the capillary wall, and how does oxygen cross?`,
 opts:[`Insulin crosses in vesicles by transcytosis; oxygen crosses by simple diffusion.`,
       `Insulin crosses by simple diffusion; oxygen crosses by transcytosis.`,
       `Both cross by bulk flow, the main route for all solutes.`,
       `Insulin passes through valves in the capillary wall; oxygen is ferried across by albumin.`,
       `Neither can cross a capillary wall; both are delivered by lymphatic vessels.`],
 ans:0, why:`Three routes across a capillary wall: diffusion (O₂, CO₂, glucose, amino acids, some hormones), transcytosis in vesicles (large lipid-insoluble molecules like insulin), and bulk flow (which mostly regulates the relative volumes of blood and interstitial fluid).`},

{n:56, topic:"vessels", obj:["V5"],
 q:`Blood flow through a tissue is the volume passing through it per unit time. Which statement about what determines it is correct?`,
 opts:[`Total blood flow equals cardiac output, and cardiac output equals mean arterial pressure divided by resistance.`,
       `Total blood flow equals mean arterial pressure multiplied by resistance.`,
       `Blood flow rises as resistance rises, because narrowing a vessel accelerates the blood.`,
       `Blood flow depends only on blood viscosity and is independent of pressure.`,
       `Blood flow equals heart rate divided by stroke volume.`],
 ans:0, why:`CO = HR × SV, and CO = MAP ÷ R. Higher pressure means more flow; higher resistance means less flow.`},

{n:57, topic:"vessels", obj:["V6"],
 q:`Blood moves most slowly through the capillaries. Why?`,
 opts:[`Velocity is inversely related to total cross-sectional area, and the capillary beds have by far the greatest total cross-sectional area.`,
       `Capillaries have the thickest walls, which creates the most friction.`,
       `Capillary blood pressure is the highest in the body, which opposes forward motion.`,
       `Capillaries contain valves that repeatedly halt the blood.`,
       `Each individual capillary is wider than the arteriole feeding it.`],
 ans:0, why:`Any one capillary is tiny, but there are so many in parallel that their combined cross-section is enormous — so the blood slows to a crawl, which is exactly what gives time for exchange. Pressure meanwhile falls steadily from aorta → arteries → arterioles → capillaries → veins.`},

{n:58, topic:"vessels", hy:1, obj:["V7"],
 q:`Vascular resistance is the opposition to blood flow from friction between blood and the vessel wall. Which three factors determine it?`,
 opts:[`The size of the vessel lumen, blood viscosity, and total blood vessel length`,
       `Heart rate, stroke volume, and cardiac reserve`,
       `Blood pH, body temperature, and hematocrit only`,
       `The number of valves, the thickness of the tunica externa, and pulse pressure`,
       `Tidal volume, respiratory rate, and minute ventilation`],
 ans:0, why:`Lumen size, viscosity and vessel length. Lumen size is the one the body actively adjusts moment to moment, by vasoconstriction and vasodilation.`},

{n:59, topic:"vessels", obj:["V7","V8"],
 q:`Which change would raise mean arterial pressure the most by increasing systemic vascular resistance?`,
 opts:[`Widespread arteriolar vasoconstriction driven by angiotensin II and ADH`,
       `Widespread arteriolar vasodilation driven by atrial natriuretic peptide and nitric oxide`,
       `A fall in blood viscosity from severe anemia`,
       `An increase in the total cross-sectional area of the capillary beds`,
       `A fall in blood volume from hemorrhage`],
 ans:0, why:`Vasoconstrictors — angiotensin II, ADH, norepinephrine and epinephrine — raise resistance and therefore pressure. ANP, nitric oxide and epinephrine at β₂ receptors dilate and lower it. Aldosterone and ADH also raise pressure by raising blood volume.`},

{n:60, topic:"vessels", obj:["V8"],
 q:`A person stands up quickly and blood pressure momentarily drops. Which structures detect the change, and where is that information processed?`,
 opts:[`Baroreceptors in the walls of blood vessels and the atria detect the reduced stretch; the cardiovascular center in the medulla oblongata responds.`,
       `Chemoreceptors in the aorta detect reduced oxygen; the pons responds by slowing the heart.`,
       `Stretch receptors in the bronchioles detect the change; the cerebellum responds.`,
       `Baroreceptors in the kidneys detect the change; the hypothalamus responds by releasing aldosterone directly.`,
       `Pacemaker cells in the SA node detect the change and respond with no neural input at all.`],
 ans:0, why:`Baroreceptors are pressure-sensitive sensory neurons monitoring stretch in vessel walls and the atria. The cardiovascular center in the medulla oblongata regulates heart rate, contractility and blood vessel diameter in response.`},

{n:61, topic:"vessels", hy:1, obj:["V9"],
 q:`A blood pressure reading is 118/76 mmHg. What is the pulse pressure, and what does the first number represent?`,
 opts:[`42 mmHg; the first number is the peak arterial pressure during ventricular contraction.`,
       `42 mmHg; the first number is the lowest arterial pressure, between beats.`,
       `194 mmHg; the first number is the sum of arterial and venous pressures.`,
       `90 mmHg; the first number is the mean arterial pressure.`,
       `76 mmHg; the first number is the pressure remaining in the aorta during diastole.`],
 ans:0, why:`Systolic pressure is the peak during ventricular contraction, diastolic is the trough between contractions, and pulse pressure is systolic − diastolic: 118 − 76 = 42 mmHg. The pulse itself is the pressure wave you feel where an artery runs near the surface.`},

{n:62, topic:"vessels", hy:1, obj:["V10"],
 q:`Shock is an inadequate cardiac output that leaves the cardiovascular system unable to meet the metabolic demands of body cells. Which set of signs fits a patient in shock?`,
 opts:[`Clammy, cool, pale skin; tachycardia with a weak rapid pulse; systolic pressure under 90 mmHg; altered mental status and decreased urine output`,
       `Flushed warm skin; bradycardia with a strong bounding pulse; systolic pressure over 160 mmHg; increased urine output`,
       `Normal skin colour, a slow regular pulse, normal blood pressure and no change in mental status`,
       `Cyanosis with a normal pulse and pressure but greatly increased urine output and alkalosis`,
       `Fever with hypertension, polycythemia and a strong bounding pulse`],
 ans:0, why:`Shock comes in hypovolemic, cardiogenic, vascular and obstructive forms. The signs reflect a body shunting blood to the core: cool clammy pale skin, thirst, sweating, tachycardia with a weak pulse, hypotension, altered mental status, low urine output and acidosis.`},

{n:63, topic:"vessels", obj:["V11","V10"],
 q:`How does the body's response to falling blood pressure illustrate negative feedback?`,
 opts:[`The drop is detected, and the responses — faster heart rate, greater contractility, vasoconstriction, fluid retention — act to reverse the drop, which then switches the response off.`,
       `The drop is detected and the responses amplify it further until a new set point is reached.`,
       `The responses run at full strength permanently, whether or not pressure is restored.`,
       `The response bypasses the nervous system entirely and relies only on autoregulation inside each tissue.`,
       `The response is triggered only after tissue death has already begun.`],
 ans:0, why:`Negative feedback opposes the change that triggered it. Baroreceptors sense the fall, the medullary cardiovascular center raises heart rate, contractility and vessel tone, pressure comes back up — and the correction shuts itself down.`},

{n:64, topic:"vessels", hy:1, obj:["V12"],
 q:`A patient's blood pressure is consistently 148/94 mmHg. Using the categories from the lecture, how is that classified?`,
 opts:[`Stage 1 hypertension`, `Normal`, `Prehypertension`, `Stage 2 hypertension`, `Hypotensive shock`],
 ans:0, why:`Normal is under 120 AND under 80; prehypertension 120–139 or 80–89; stage 1 is 140–159 or 90–99; stage 2 is above 160 or above 100. 148/94 lands in stage 1 on both numbers.`},

/* ==================== RESPIRATORY SYSTEM · 16 ==================== */
{n:65, topic:"resp", hy:1, obj:["R1"],
 q:`The respiratory tract divides into a conducting zone and a respiratory zone. Which structures make up the respiratory zone?`,
 opts:[`Respiratory bronchioles, alveolar ducts and alveoli`,
       `Nose, pharynx, larynx, trachea and bronchi`,
       `Terminal bronchioles, trachea and primary bronchi`,
       `Pharynx, larynx and trachea only`,
       `The pleural cavity and the diaphragm`],
 ans:0, why:`The split is by job: the conducting zone (nose → pharynx → larynx → trachea → bronchi → bronchioles) moves air, while the respiratory zone (respiratory bronchioles → alveolar ducts → alveolar sacs → alveoli) is where gas exchange happens.`},

{n:66, topic:"resp", hy:1, obj:["R1","R8"],
 q:`Which pairing of respiratory process and definition is correct?`,
 opts:[`External respiration is gas exchange between the lungs and the blood; internal respiration is gas exchange between systemic vessels and the tissues.`,
       `External respiration is gas exchange between systemic vessels and the tissues; internal respiration happens in the lungs.`,
       `Pulmonary ventilation is the exchange of gases across the respiratory membrane.`,
       `Internal respiration is the movement of air into and out of the lungs.`,
       `External respiration is the production of ATP inside the mitochondria of body cells.`],
 ans:0, why:`Four processes: pulmonary ventilation (breathing), external respiration (lungs ↔ blood), transport of O₂ and CO₂ in the blood, and internal respiration (blood ↔ tissues).`},

{n:67, topic:"resp", obj:["R2","R4"],
 q:`Which list correctly gives the functions of the nose?`,
 opts:[`Provides an airway, warms and moistens incoming air, filters and cleans it, acts as a resonating chamber for speech, and houses the olfactory receptors.`,
       `Provides an airway, exchanges O₂ and CO₂ with the blood, and produces surfactant.`,
       `Filters air, produces the vocal sounds themselves, and seals the airway during swallowing.`,
       `Warms air, houses the tonsils, and serves as the shared passageway for air and food.`,
       `Filters air, secretes pleural fluid, and anchors the lungs to the mediastinum.`],
 ans:0, why:`Airway, warming, moistening, filtering, resonance for speech, and smell. Housing the tonsils and doubling as a food passage are jobs of the pharynx.`},

{n:68, topic:"resp", obj:["R3","R2"],
 q:`Which statement about the larynx is correct?`,
 opts:[`Its epiglottis is elastic cartilage that covers the laryngeal inlet during swallowing, and the glottis is the opening between the vocal folds.`,
       `Its epiglottis is hyaline cartilage that holds the airway open during swallowing.`,
       `The thyroid cartilage is the opening between the vocal folds, and the glottis is the Adam's apple.`,
       `The true vocal cords make sound as air is drawn inward during inhalation.`,
       `The larynx connects the nasal cavity to the esophagus and carries only food.`],
 ans:0, why:`The larynx connects pharynx to trachea and contains the thyroid cartilage (Adam's apple), epiglottis, cricoid and arytenoid cartilages, and the false and true vocal cords. The epiglottis is elastic cartilage — not hyaline — and the vocal folds vibrate as air is expelled.`},

{n:69, topic:"resp", hy:1, obj:["R3","R5"],
 q:`The tracheal wall has three layers. Which description is correct?`,
 opts:[`A mucosa of ciliated pseudostratified epithelium with goblet cells, a submucosa supported by 16–20 C-shaped hyaline cartilage rings, and an outer adventitia of connective tissue.`,
       `A mucosa of simple squamous epithelium, a submucosa of skeletal muscle, and an adventitia of elastic cartilage.`,
       `A mucosa of stratified squamous epithelium, a submucosa with complete rings of elastic cartilage, and no adventitia.`,
       `A single layer of endothelial cells on a basement membrane, like a capillary.`,
       `A mucosa of cuboidal epithelium with surfactant-secreting cells and a submucosa of smooth muscle only.`],
 ans:0, why:`The rings are C-shaped and incomplete so the esophagus can bulge forward during swallowing, and they keep the trachea from collapsing. The cilia sweep mucus upward — which is what smoking destroys, leaving coughing as the only way to clear it.`},

{n:70, topic:"resp", obj:["R3","R5"],
 q:`As the airways branch from the bronchi down into the bronchioles, which set of changes occurs?`,
 opts:[`Cartilage rings become irregular plates and are finally replaced by elastic fibers, pseudostratified columnar epithelium gives way to cuboidal, cilia and goblet cells grow sparse, and the amount of smooth muscle increases.`,
       `Cartilage becomes more complete and ring-like, the epithelium grows taller, and smooth muscle disappears.`,
       `The epithelium changes to stratified squamous and goblet cells become far more numerous.`,
       `Smooth muscle disappears entirely, which is why bronchioles offer no resistance to airflow.`,
       `The wall thins to a single squamous layer as soon as the primary bronchi enter the lung.`],
 ans:0, why:`Support shifts from cartilage to elastic fiber and smooth muscle — which is exactly why bronchioles can provide substantial resistance to airflow, and why bronchoconstriction (parasympathetic) versus bronchodilation (sympathetic) matters clinically.`},

{n:71, topic:"resp", hy:1, obj:["R4","R5"],
 q:`Which alveolar cell secretes surfactant, and what does surfactant do?`,
 opts:[`Type II alveolar cells; surfactant reduces surface tension so the alveoli do not collapse.`,
       `Alveolar macrophages; surfactant engulfs inhaled debris.`,
       `Type I alveolar cells; surfactant thickens the respiratory membrane to slow diffusion.`,
       `Goblet cells; surfactant traps particles in mucus.`,
       `Type II alveolar cells; surfactant raises surface tension so the alveoli recoil faster.`],
 ans:0, why:`Type II alveolar cells make surfactant, which lowers surface tension and keeps alveoli from collapsing. Alveolar macrophages are the separate debris-eaters. About 300 million alveoli make up most of the lung's volume.`},

{n:72, topic:"resp", obj:["R3","R5"],
 q:`Which statement about the lungs and their coverings is correct?`,
 opts:[`The visceral pleura covers the lung surface and the parietal pleura lines the thoracic wall, with pleural fluid between them; the right lung has three lobes and the left has two.`,
       `The parietal pleura covers the lung surface and the visceral pleura lines the thoracic wall; the right lung has two lobes and the left has three.`,
       `One continuous pleural membrane surrounds both lungs, and each lung has three lobes.`,
       `The visceral pleura covers the lung surface, and both lungs have two lobes because the heart sits in the midline.`,
       `The pleurae are continuous with the pericardium, and pleural fluid is made by type II alveolar cells.`],
 ans:0, why:`Visceral = on the organ, parietal = on the wall. Right lung: superior, middle, inferior lobes. Left lung: superior and inferior only. The apex sits deep to the clavicle, the base rests on the diaphragm, and the root is where vessels and bronchi attach to the mediastinum.`},

{n:73, topic:"resp", hy:1, obj:["R6"],
 q:`What makes air flow into the lungs during quiet inhalation?`,
 opts:[`The diaphragm and external intercostals contract, thoracic volume rises, and intrapulmonary pressure falls below atmospheric pressure.`,
       `The diaphragm relaxes and domes upward, raising intrapulmonary pressure above atmospheric pressure.`,
       `Intrapleural pressure becomes positive relative to intrapulmonary pressure, pushing the lungs open.`,
       `Air is actively pumped into the alveoli by contraction of alveolar smooth muscle.`,
       `Surfactant increases surface tension, pulling the alveolar walls apart.`],
 ans:0, why:`Air moves down a pressure gradient. Contracting the diaphragm and external intercostals enlarges the thorax, which drops intrapulmonary pressure below the 760 mmHg outside, and air flows in. Quiet exhalation is the passive reverse.`},

{n:74, topic:"resp", obj:["R6","R11"],
 q:`Why is intrapleural pressure always negative relative to intrapulmonary pressure, and why does that matter?`,
 opts:[`That pressure difference is what holds the lungs expanded against their own elastic recoil; lose it and the lung collapses.`,
       `It is negative because the pleural cavity is filled with air at 760 mmHg, which props the lung open.`,
       `It is negative only during exhalation, which is why exhalation is normally an active process.`,
       `It matters only because it drives gas exchange across the respiratory membrane.`,
       `It is negative because surfactant actively pumps fluid out of the pleural cavity.`],
 ans:0, why:`Intrapleural pressure is always lower than intrapulmonary pressure, and that transpulmonary gradient keeps the lungs from collapsing. Puncture the pleural space and the gradient is gone — the lung collapses.`},

{n:75, topic:"resp", hy:1, obj:["R7"],
 q:`Which equation correctly defines vital capacity?`,
 opts:[`VC = tidal volume + inspiratory reserve volume + expiratory reserve volume`,
       `VC = tidal volume + residual volume`,
       `VC = total lung capacity + residual volume`,
       `VC = inspiratory reserve volume + residual volume`,
       `VC = tidal volume × respiratory rate`],
 ans:0, why:`Vital capacity is the total amount of exchangeable air: TV + IRV + ERV. Total lung capacity adds the air you cannot exhale: TLC = VC + RV.`},

{n:76, topic:"resp", obj:["R7"],
 q:`Which volume cannot be measured with a simple spirometer, because it cannot be voluntarily exhaled?`,
 opts:[`Residual volume`, `Tidal volume`, `Inspiratory reserve volume`, `Expiratory reserve volume`, `Minute ventilation`],
 ans:0, why:`Residual volume is the air left in the lungs after the most forceful exhalation, so a spirometer never sees it. Minute ventilation is the total volume moved per minute — that one is measurable.`},

{n:77, topic:"resp", obj:["R8"],
 q:`What determines the direction O₂ and CO₂ move during external and internal respiration?`,
 opts:[`Each gas diffuses from where its partial pressure is higher to where its partial pressure is lower.`,
       `Each gas is actively transported across the respiratory membrane by carrier proteins.`,
       `Both gases move in the same direction, following the flow of blood.`,
       `Oxygen moves by bulk flow and carbon dioxide by transcytosis.`,
       `The direction is set by total air pressure, not by any individual gas.`],
 ans:0, why:`Partial pressure gradients, and nothing else. In the lungs alveolar P_O₂ is higher than in the capillary so O₂ diffuses in, while blood P_CO₂ is higher so CO₂ diffuses out. At the tissues both gradients reverse.`},

{n:78, topic:"resp", hy:1, obj:["R9"],
 q:`How is most carbon dioxide carried in the blood?`,
 opts:[`About 70% as bicarbonate ions`,
       `About 70% bound to hemoglobin as carbaminohemoglobin`,
       `About 70% dissolved in plasma as free CO₂`,
       `About 98.5% bound to hemoglobin as oxyhemoglobin`,
       `Entirely inside erythrocytes, bound to carbonic anhydrase`],
 ans:0, why:`CO₂ travels three ways: ~70% as bicarbonate, ~23% as carbaminohemoglobin, ~7% dissolved in plasma. Oxygen is the one that is ~98.5% bound to hemoglobin, as oxyhemoglobin.`},

{n:79, topic:"resp", hy:1, obj:["R10"],
 q:`Which chemical factor is the main regulator of respiratory rate and depth, and where does it act?`,
 opts:[`Carbon dioxide — rising CO₂ lowers blood pH and acts directly on the medulla oblongata to increase respiration.`,
       `Oxygen — falling O₂ acts directly on the medulla and is the primary drive to breathe.`,
       `Bicarbonate — rising HCO₃⁻ acts on the pons to smooth out the respiratory rhythm.`,
       `Carbon dioxide — rising CO₂ acts on stretch receptors in the bronchioles to trigger inspiration.`,
       `Oxygen — rising O₂ acts on the phrenic nerve to deepen breathing.`],
 ans:0, why:`CO₂ is the main regulatory chemical, acting directly on the medulla oblongata. The medulla sets the basic rhythm and the pons smooths it; the phrenic and intercostal nerves drive the muscles; oxygen changes are picked up by chemoreceptors in the aorta and carotid arteries.`},

{n:80, topic:"resp", obj:["R11"],
 q:`A patient has laryngitis. Which description matches that disorder?`,
 opts:[`Inflammation of the vocal folds that makes them swell and interferes with vibration, causing hoarseness or reducing speech to a whisper.`,
       `Inflammation of the nasal mucosa that spreads to the paranasal sinuses and produces a sinus headache.`,
       `Enlargement of the adenoids that blocks the nasopharynx and forces mouth breathing.`,
       `Destruction of the tracheal cilia, so coughing becomes the only way to clear mucus.`,
       `Collapse of the alveoli caused by a lack of surfactant.`],
 ans:0, why:`Laryngitis is usually viral but can come from overusing the voice, very dry air, bacterial infection, tumors on the folds, or inhaled irritants. The nasal-mucosa answer describes rhinitis leading to sinusitis.`},
];
