/* BIOL 40B — Lecture Exam 2 · FORM B (80 questions)
   A second, independent form over the same five decks and the same weighting
   (Blood 19 · Heart 13 · Cardiac physiology 16 · Blood vessels 16 · Respiratory 16).
   Different questions and different angles from Form A, but the objective coverage is
   the same — every objective in objectives_data.js is tested here too, so either form
   on its own covers the whole list.

   Same convention as Form A: the correct option is authored first (ans:0) for easy
   auditing, and the engine shuffles the five choices on every render. */
const EXAM_B = [

/* ============================ BLOOD · 19 ============================ */
{n:1, topic:"blood", hy:1, obj:["B1"],
 q:`During hard exercise a patient overheats, and blood is shunted to vessels near the skin so heat can escape. Which general function of blood does this illustrate, and what structure sets the body's temperature?`,
 opts:[`Regulation — and the hypothalamus is the body's thermostat.`,
       `Protection — and the medulla oblongata is the body's thermostat.`,
       `Transportation — and the thyroid gland is the body's thermostat.`,
       `Regulation — and the pituitary gland is the body's thermostat.`,
       `Protection — and the skin itself sets the temperature set point.`],
 ans:0, why:`Blood's three functions are transportation, regulation (pH, temperature, fluid balance) and protection. Normal body temperature is about 98.6 °F / 37 °C, regulated by the hypothalamus.`},

{n:2, topic:"blood", obj:["B2","B3"],
 q:`What fraction of total blood volume is plasma, and what is plasma mostly made of?`,
 opts:[`About 55% plasma — roughly 90% water, with dissolved proteins, electrolytes, gases, nutrients and wastes.`,
       `About 55% plasma — roughly 90% protein, with a little dissolved water.`,
       `About 45% plasma — roughly half water and half fibrin.`,
       `About 90% plasma, with the remaining 10% split evenly among the formed elements.`,
       `About 20% plasma, since erythrocytes occupy nearly all the blood volume.`],
 ans:0, why:`Hematocrit (packed cells) is about 45%, so plasma is about 55%. Plasma itself is about 90% water plus dissolved compounds.`},

{n:3, topic:"blood", obj:["B2"],
 q:`Which statement correctly matches each formed element to its defining structural feature?`,
 opts:[`Erythrocytes are biconcave and have no nucleus; leukocytes are complete nucleated cells; platelets are anucleate cell fragments.`,
       `Erythrocytes are nucleated; leukocytes are anucleate fragments; platelets are complete cells.`,
       `All three are complete nucleated cells that can divide in the bloodstream.`,
       `Erythrocytes are cell fragments; platelets are biconcave discs; leukocytes are anucleate.`,
       `Erythrocytes and platelets both have nuclei; only leukocytes lack one.`],
 ans:0, why:`Only the leukocytes are complete cells. RBCs eject their nucleus and organelles; platelets were never whole cells at all — they are fragments of megakaryocytes.`},

{n:4, topic:"blood", obj:["B3"],
 q:`Which group of plasma constituents includes sodium, potassium, calcium, magnesium, chloride and bicarbonate?`,
 opts:[`The plasma electrolytes`, `The plasma proteins`, `The formed elements`, `The clotting factors`, `The immunoglobulins`],
 ans:0, why:`Plasma is ~90% water carrying proteins (albumin, antibodies, clotting proteins) plus electrolytes, nutrients, gases, hormones and wastes.`},

{n:5, topic:"blood", obj:["B3"],
 q:`A patient with liver failure cannot make enough albumin. Based on albumin's role, what would you expect?`,
 opts:[`Fluid leaks out of the capillaries into the tissues, because the blood's colloid osmotic pressure has fallen.`,
       `Blood becomes too viscous to flow, because albumin normally thins the plasma.`,
       `Clotting fails completely, because albumin is the direct precursor of fibrin.`,
       `Oxygen-carrying capacity drops sharply, because albumin carries most of the blood's oxygen.`,
       `The patient becomes immunodeficient, because albumin is the main antibody of plasma.`],
 ans:0, why:`Plasma proteins — albumin above all — hold water inside the vessels by osmotic pressure. Lose albumin and fluid escapes into the interstitial space.`},

{n:6, topic:"blood", obj:["B4"],
 q:`Erythrocytes have no organelles, but they do carry enzymes in the cytoplasm. What does carbonic anhydrase do there?`,
 opts:[`It converts CO₂ into bicarbonate, which is how most carbon dioxide is transported in blood.`,
       `It splits hemoglobin into globin and heme so oxygen can be released.`,
       `It runs the Krebs cycle so the cell can make ATP aerobically.`,
       `It converts bilirubin into bile salts for excretion by the liver.`,
       `It binds iron so hemoglobin can be assembled inside the cell.`],
 ans:0, why:`RBCs carry glycolytic enzymes (for anaerobic ATP) and carbonic anhydrase, which converts CO₂ to HCO₃⁻ — the form ~70% of blood CO₂ travels in.`},

{n:7, topic:"blood", hy:1, obj:["B4"],
 q:`Carbon monoxide binds hemoglobin far more tightly than oxygen does. What is the resulting compound called, and why is CO poisoning so dangerous?`,
 opts:[`Carboxyhemoglobin — CO occupies the iron-binding sites so hemoglobin cannot pick up oxygen, and tissues go hypoxic even while breathing looks normal.`,
       `Carbaminohemoglobin — CO binds the globin chains and forces hemoglobin to dump all its oxygen at once.`,
       `Oxyhemoglobin — CO increases oxygen loading, and the danger is oxygen toxicity.`,
       `Deoxyhemoglobin — CO strips the iron out of heme, which the kidneys then excrete.`,
       `Methemoglobin — CO makes the RBCs sickle and block small vessels.`],
 ans:0, why:`Don't confuse the names: oxyhemoglobin is O₂-loaded (ruby red), deoxyhemoglobin is unloaded (dark red), carbaminohemoglobin is CO₂ bound to Hb (~20–23% of blood CO₂), and carboxyhemoglobin is the carbon-monoxide compound.`},

{n:8, topic:"blood", hy:1, obj:["B4"],
 q:`A new erythrocyte enters the bloodstream. About how long does it survive, and what becomes of it?`,
 opts:[`About 120 days, after which it is destroyed by the spleen or liver.`,
       `About 15 days, after which it matures into a reticulocyte in the marrow.`,
       `A few hours to a few days, after which neutrophils phagocytize it.`,
       `About 35 days, after which the kidneys excrete it intact.`,
       `Indefinitely, since erythrocytes divide to replace themselves.`],
 ans:0, why:`Red bone marrow makes about 3 million RBCs per second. A hemocytoblast takes ~15 days to reach the reticulocyte stage, and the reticulocyte matures in the bloodstream in ~2 days. Leukocytes are the ones that live only hours to days; 35 days is the shelf life of banked blood.`},

{n:9, topic:"blood", hy:1, obj:["B5"],
 q:`A patient's erythrocytes are described as small, pale microcytes. What anemia is this, and why do the cells look that way?`,
 opts:[`Iron-deficiency anemia; without iron the cells cannot synthesize enough hemoglobin.`,
       `Pernicious anemia; without vitamin B₁₂ the cells cannot divide and stay abnormally large.`,
       `Aplastic anemia; the marrow is destroyed and makes no cells at all.`,
       `Renal anemia; too little EPO shrinks each individual cell.`,
       `Sickle-cell anemia; one amino acid substitution distorts the cell's shape.`],
 ans:0, why:`Iron-deficiency anemia can come from chronic blood loss, low iron intake or impaired absorption. Hemoglobin is what makes an RBC red, so iron-starved cells are both small and pale. Treatment is iron supplements.`},

{n:10, topic:"blood", obj:["B5"],
 q:`A patient exposed to radiation develops anemia plus clotting defects plus immune deficiency. What does that combination tell you?`,
 opts:[`Aplastic anemia — the red bone marrow itself has been destroyed or inhibited, so every formed-element cell line is affected.`,
       `Iron-deficiency anemia — only the erythrocyte line is affected, but severely.`,
       `Polycythemia vera — the marrow overproduces every cell line at once.`,
       `Pernicious anemia — the stomach mucosa no longer makes intrinsic factor.`,
       `Thrombocytopenia — only the platelet line is suppressed.`],
 ans:0, why:`Hit the marrow and you lose all three lines at once: too few RBCs (anemia), too few platelets (bleeding) and too few WBCs (infection). Causes include drugs, chemicals, radiation and viruses; treatment is transfusion short-term and transplanted stem cells long-term.`},

{n:11, topic:"blood", obj:["B5"],
 q:`A patient has bled slightly but persistently from a gastric ulcer for months. What type of anemia is this, and what has to happen first?`,
 opts:[`Chronic hemorrhagic anemia; the underlying source of blood loss must be treated to stop the bleeding.`,
       `Acute hemorrhagic anemia; whole-blood transfusion alone is the complete treatment.`,
       `Aplastic anemia; the patient needs a stem cell transplant.`,
       `Renal anemia; the patient needs synthetic erythropoietin.`,
       `Pernicious anemia; the patient needs vitamin B₁₂ injections.`],
 ans:0, why:`Acute hemorrhagic anemia follows rapid loss such as a severe wound; chronic hemorrhagic anemia follows slight persistent loss such as hemorrhoids or a bleeding ulcer. Either way the primary problem has to be fixed or the loss continues.`},

{n:12, topic:"blood", obj:["B6"],
 q:`Which set of jobs belongs to the leukocytes?`,
 opts:[`Protecting against infection, initiating inflammation, destroying cancerous cells, and assisting tissue repair`,
       `Transporting oxygen and carbon dioxide between the lungs and the tissues`,
       `Forming the platelet plug and generating fibrin threads`,
       `Maintaining blood osmotic pressure and transporting bilirubin`,
       `Producing erythropoietin in response to low blood oxygen`],
 ans:0, why:`Leukocytes are the defensive line: infection control, inflammation, killing cancerous cells and helping repair tissue. Most live only hours to a few days.`},

{n:13, topic:"blood", hy:1, obj:["B6"],
 q:`Which statement about the agranulocytes is correct?`,
 opts:[`Monocytes leave the blood, enter the tissues and mature into macrophages; the lymphocytes are B cells, T cells and NK cells.`,
       `Monocytes release histamine, and lymphocytes mature into macrophages while still in the bloodstream.`,
       `B cells regulate the immune response while T cells become plasma cells and secrete antibodies.`,
       `NK cells produce antibodies against specific bacterial toxins.`,
       `Monocytes are granulocytes, and lymphocytes are the most abundant WBC in normal blood.`],
 ans:0, why:`B cells develop into plasma cells that make antibodies, T cells regulate the immune response, and NK cells attack a broad range of microbes and tumor cells. Histamine is a basophil product.`},

{n:14, topic:"blood", obj:["B7"],
 q:`Once platelets have stuck to a damaged vessel wall, they release chemicals. What do those chemicals do?`,
 opts:[`Attract more platelets to the site and cause vasoconstriction.`,
       `Inhibit further platelet aggregation and dilate the vessel.`,
       `Dissolve the fibrin mesh so blood can keep flowing.`,
       `Convert plasmin into plasminogen.`,
       `Destroy exposed collagen so platelets stop sticking.`],
 ans:0, why:`This is the positive-feedback part of platelet plug formation — activated platelets recruit more platelets and narrow the vessel. Prostacyclin and nitric oxide from healthy endothelium do the opposite.`},

{n:15, topic:"blood", obj:["B7","B8"],
 q:`Once a clot has done its job and the vessel is healing, which process removes it, and what enzyme does the work?`,
 opts:[`Fibrinolysis — tPA and urokinase convert plasminogen into plasmin, and plasmin digests the fibrin.`,
       `Coagulation — thrombin converts plasmin into fibrin, which dissolves the clot.`,
       `Clot retraction — platelets convert fibrin directly into serum.`,
       `Vascular spasm — smooth muscle contraction squeezes the clot out of the vessel.`,
       `Hemostasis — factor XIII digests the platelet plug from the inside.`],
 ans:0, why:`First clot retraction: trapped platelets contract, squeeze out serum, and attract fibroblasts that repair the wall. Then fibrinolysis: tPA/urokinase → plasminogen becomes plasmin → plasmin breaks down fibrin.`},

{n:16, topic:"blood", hy:1, obj:["B8"],
 q:`Which statement correctly distinguishes the two arms of the clotting cascade?`,
 opts:[`The intrinsic pathway begins when Hageman factor is activated by exposed collagen; the extrinsic pathway begins when thromboplastin from damaged tissue activates factor X.`,
       `The intrinsic pathway begins with thromboplastin from damaged tissue; the extrinsic pathway begins with exposed collagen.`,
       `The intrinsic pathway needs no clotting factors; the extrinsic pathway needs all thirteen.`,
       `The intrinsic pathway requires calcium; the extrinsic pathway works without it.`,
       `The two pathways never converge — each makes its own separate kind of clot.`],
 ans:0, why:`Both arms funnel into the same final step, where thrombin converts fibrinogen to fibrin. The cascade involves 13 clotting factors and requires Ca²⁺ throughout.`},

{n:17, topic:"blood", obj:["B8"],
 q:`Which event is the immediate first response when a blood vessel is cut?`,
 opts:[`Vascular spasm — smooth muscle in the vessel wall constricts, narrowing the vessel and cutting blood loss.`,
       `Fibrin threads polymerize across the tear before anything else happens.`,
       `The platelet plug forms first, and only afterward does the vessel constrict.`,
       `Plasmin is released to keep the vessel open.`,
       `Erythropoietin is released to replace the lost cells immediately.`],
 ans:0, why:`Vascular spasm is step 1 of hemostasis, followed by platelet plug formation and coagulation — though in practice all three overlap in time.`},

{n:18, topic:"blood", hy:1, obj:["B9"],
 q:`A patient with a platelet count of 40,000/µL has small purple spots appearing across the skin. What are the spots, and what is the diagnosis?`,
 opts:[`Petechiae from spontaneous widespread hemorrhage; the diagnosis is thrombocytopenia.`,
       `Emboli lodged in dermal capillaries; the diagnosis is polycythemia vera.`,
       `Hemophilia A bleeding into the skin; the diagnosis is a factor VIII deficiency.`,
       `Sickled cells blocking dermal vessels; the diagnosis is sickle-cell anemia.`,
       `Leukemic infiltrates; the diagnosis is chronic myeloid leukemia.`],
 ans:0, why:`A platelet count below 50,000/µL is diagnostic for thrombocytopenia, treated with transfused concentrated platelets. Hemophilia A (factor VIII, 77% of cases) characteristically bleeds into joint cavities instead.`},

{n:19, topic:"blood", hy:1, obj:["B10"],
 q:`Which combination of surface antigen and plasma antibody defines type O blood?`,
 opts:[`Neither A nor B antigen on the cells, with both anti-A and anti-B antibodies in the plasma.`,
       `Both A and B antigens on the cells, with neither anti-A nor anti-B in the plasma.`,
       `A antigen on the cells, with anti-A antibodies in the plasma.`,
       `B antigen on the cells, with anti-B antibodies in the plasma.`,
       `Neither A nor B antigen on the cells, and no antibodies in the plasma.`],
 ans:0, why:`You carry antibodies against the antigens you lack — so type O has both. Type AB is the mirror image: both antigens, neither antibody. Options 3 and 4 are impossible; you never carry an antibody against your own antigen.`},

/* ======================= HEART ANATOMY · 13 ======================= */
{n:20, topic:"heart", hy:1, obj:["H1"],
 q:`Which layer of the heart wall is the thick middle layer of contractile cardiac muscle arranged in circular and spiral bundles?`,
 opts:[`Myocardium`, `Endocardium`, `Epicardium`, `Fibrous pericardium`, `Parietal layer of the serous pericardium`],
 ans:0, why:`Three layers, outside in: epicardium (which is the visceral serous pericardium), myocardium (the muscle that does the work), and endocardium — the innermost lining, continuous with the endothelium of the blood vessels and covering the valves.`},

{n:21, topic:"heart", obj:["H1"],
 q:`Which features belong to the ventricles rather than the atria?`,
 opts:[`Thick walls, trabeculae carneae, and papillary muscles anchoring the chordae tendineae`,
       `Auricles and pectinate muscles`,
       `Thin walls that add little to the propulsion of blood`,
       `The interatrial septum`,
       `The openings of the superior and inferior vena cava`],
 ans:0, why:`Ventricles are the actual pumps and make up most of the heart's volume — the right ventricle forms most of the anterior surface, the left the posteroinferior surface. Auricles, pectinate muscles and the interatrial septum are atrial features.`},

{n:22, topic:"heart", obj:["H1"],
 q:`Which valve sits at the opening where the pulmonary trunk leaves the right ventricle, and how is it built?`,
 opts:[`The pulmonary valve — three semilunar cusps that attach to the artery wall`,
       `The tricuspid valve — three cusps anchored by chordae tendineae`,
       `The aortic valve — two semilunar cusps`,
       `The bicuspid (mitral) valve — two cusps`,
       `The pulmonary valve — two cusps anchored to papillary muscles`],
 ans:0, why:`Both semilunar valves (pulmonary and aortic) have three half-moon cusps attached to the artery wall and no chordae tendineae — those belong to the AV valves.`},

{n:23, topic:"heart", hy:1, obj:["H1"],
 q:`Which valve lies between the left atrium and the left ventricle, and how many cusps does it have?`,
 opts:[`The bicuspid (mitral) valve — two cusps`,
       `The tricuspid valve — three cusps`,
       `The aortic valve — three semilunar cusps`,
       `The bicuspid valve — three cusps`,
       `The pulmonary valve — two cusps`],
 ans:0, why:`Left side is bicuspid/mitral with two cusps; right side is tricuspid with three. Both are AV valves anchored by chordae tendineae to papillary muscles.`},

{n:24, topic:"heart", obj:["H1","C10"],
 q:`A patient's valve flaps have stiffened, narrowing the opening so the heart must push harder to move blood through. What is this, and how does it differ from an incompetent valve?`,
 opts:[`Valvular stenosis; an incompetent valve instead lets blood backflow, so the heart repumps the same blood over and over.`,
       `An incompetent valve; valvular stenosis instead lets blood leak backward through the valve.`,
       `Cardiac tamponade; an incompetent valve is caused by fluid in the pericardial cavity.`,
       `Pericarditis; an incompetent valve is caused by inflammation of the endocardium.`,
       `Heart block; an incompetent valve is caused by damage to the AV node.`],
 ans:0, why:`Both conditions severely weaken the heart — stenosis by making it work harder against a narrowed opening, incompetence by making it pump the same blood repeatedly. A defective valve can be replaced with a mechanical, animal or cadaver valve.`},

{n:25, topic:"heart", obj:["H2"],
 q:`Which statement correctly defines the heart's two main circuits?`,
 opts:[`The pulmonary circulation carries blood to the lungs for gas exchange and returns it to the heart; the systemic circulation carries blood to the body tissues and returns it.`,
       `The pulmonary circulation carries blood to the body tissues; the systemic circulation carries blood to the lungs.`,
       `Both circuits deliver oxygenated blood to tissue and differ only in vessel size.`,
       `The pulmonary circulation begins in the left ventricle and the systemic circulation in the right ventricle.`,
       `The coronary circulation is a branch of the pulmonary circulation.`],
 ans:0, why:`Pulmonary circuit: right ventricle → lungs → left atrium. Systemic circuit: left ventricle → body → right atrium. Coronary circulation is the third, supplying the myocardium itself.`},

{n:26, topic:"heart", hy:1, obj:["H2"],
 q:`Why is the wall of the left ventricle so much thicker than that of the right?`,
 opts:[`The left ventricle must generate enough pressure to drive blood through the whole systemic circuit, while the right ventricle only pumps as far as the lungs.`,
       `The left ventricle holds far more blood than the right ventricle.`,
       `The left ventricle houses the conduction system and needs extra muscle around it.`,
       `The right ventricle is thinner because it receives most of the coronary blood supply.`,
       `The left ventricle must overcome the pulmonary valve, which is the stiffest valve in the heart.`],
 ans:0, why:`Same volume per beat, very different workload. The systemic circuit has far higher resistance than the pulmonary circuit, so the left ventricle needs much more muscle.`},

{n:27, topic:"heart", hy:1, obj:["H2"],
 q:`How many pulmonary veins return blood to the heart, which chamber do they enter, and what kind of blood do they carry?`,
 opts:[`Four; they enter the left atrium; they carry oxygenated blood.`,
       `Two; they enter the right atrium; they carry deoxygenated blood.`,
       `Four; they enter the right atrium; they carry oxygenated blood.`,
       `One; it enters the left ventricle; it carries oxygenated blood.`,
       `Four; they enter the left atrium; they carry deoxygenated blood.`],
 ans:0, why:`The pulmonary veins are the exception to the "veins carry deoxygenated blood" rule — four of them return freshly oxygenated blood from the lungs to the left atrium.`},

{n:28, topic:"heart", obj:["H2"],
 q:`The coronary arteries contain many anastomoses. Why does that matter clinically?`,
 opts:[`An anastomosis is a junction between vessels that provides an alternate route for blood, so it offers some protection if one branch narrows.`,
       `Anastomoses are the valves of the coronary arteries and stop backflow into the aorta.`,
       `Anastomoses are dead-end branches, so blocking one always causes immediate necrosis.`,
       `Anastomoses are where the coronary arteries drain directly into the coronary sinus.`,
       `Anastomoses let the coronary arteries fill during systole rather than diastole.`],
 ans:0, why:`Where two or more arteries supplying a region join, blood has a detour available. Arteries with no anastomosis are "end arteries" — block one and that region has no alternative supply, so necrosis follows.`},

{n:29, topic:"heart", obj:["H3","H4"],
 q:`Which statement about the two kinds of cardiac myocytes is correct?`,
 opts:[`Contractile cells do the pumping; pacemaker cells are noncontractile cells that spontaneously depolarize and trigger depolarization of the entire heart without nervous stimulation.`,
       `Contractile cells depolarize spontaneously, while pacemaker cells do the pumping.`,
       `Both types must be stimulated by a motor neuron, exactly as skeletal muscle fibers are.`,
       `Pacemaker cells make up 99% of the myocardium and generate the force of contraction.`,
       `Contractile cells cannot be excited by their neighbours because they have no gap junctions.`],
 ans:0, why:`99% of the heart is contractile cells; ~1% are self-excitable autorhythmic cells. Unlike skeletal muscle, the heart needs no nervous input to contract — the nervous system only modulates the rate.`},

{n:30, topic:"heart", obj:["H3"],
 q:`What is the specific job of the Purkinje fibers?`,
 opts:[`To distribute the impulse from the heart apex evenly through the walls of both ventricles, causing them to contract.`,
       `To delay the impulse so the atria can finish contracting.`,
       `To generate the original impulse that sets the heart rate.`,
       `To carry the impulse from the SA node to the AV node across the atria.`,
       `To anchor the AV valve cusps to the papillary muscles.`],
 ans:0, why:`The bundle branches carry the impulse toward the apex, and Purkinje fibers spread it from the apex up through the ventricular walls — so the ventricles squeeze from the bottom upward, toward the outflow valves.`},

{n:31, topic:"heart", obj:["H3","C10"],
 q:`An overly excitable patch of myocardium starts depolarizing faster than the SA node. What is that patch called, and what can it cause?`,
 opts:[`An ectopic focus; it can produce a premature heartbeat (extrasystole) and/or a faster heart rate.`,
       `A heart block; it stops the ventricles from contracting at all.`,
       `An anastomosis; it reroutes the impulse around the AV node.`,
       `An intercalated disc; it slows conduction between cells.`,
       `A pacemaker potential; it stops the SA node from ever firing again.`],
 ans:0, why:`Whatever depolarizes fastest sets the rhythm. An ectopic focus can be provoked by heart disease and hypoxia, but also by anxiety, lack of sleep, and too much caffeine or nicotine.`},

{n:32, topic:"heart", hy:1, obj:["H4"],
 q:`What is the functional role of the gap junctions within the intercalated discs?`,
 opts:[`They let ions pass freely from cell to cell, so a depolarization wave spreads through the myocardium and the whole muscle mass contracts as one unit.`,
       `They mechanically anchor the cardiac cells together but block all ion movement.`,
       `They store calcium for release during contraction.`,
       `They insulate each cell so the SA node has to stimulate every myocyte individually.`,
       `They connect cardiac muscle cells to the fibrous skeleton of the valves.`],
 ans:0, why:`Intercalated discs do two things at once: anchor the cells mechanically and pass ions electrically through gap junctions. That is what makes the myocardium a functional syncytium — all cells contract, or none do.`},

/* ==================== CARDIAC PHYSIOLOGY · 16 ==================== */
{n:33, topic:"cardio", obj:["C1"],
 q:`What is the role of the intrinsic conduction system, and how does its signal reach the ordinary myocardial cells?`,
 opts:[`It coordinates rhythmic excitation and contraction so the heart pumps efficiently, and its action potential spreads to the surrounding myocardium through gap junctions.`,
       `It supplies the myocardium with oxygen, and the signal spreads through the coronary arteries.`,
       `It relays motor commands from the medulla, and the signal spreads along the phrenic nerve.`,
       `It physically fuses the atria and ventricles so they cannot contract at different times.`,
       `It generates the force of contraction directly, since autorhythmic cells are 99% of the heart.`],
 ans:0, why:`The autorhythmic cells of the conduction system generate the action potential; gap junctions then hand it off cell to cell through the contractile myocardium.`},

{n:34, topic:"cardio", hy:1, obj:["C2"],
 q:`Put the events of an action potential in a cardiac CONTRACTILE cell in the correct order.`,
 opts:[`Depolarization arrives through gap junctions → fast Na⁺ channels open → Na⁺ channels close and slow Ca²⁺ channels open (plateau) → Ca²⁺ channels close and K⁺ channels open (repolarization)`,
       `Slow Ca²⁺ channels open → fast Na⁺ channels open → K⁺ channels open → the cell hyperpolarizes below its resting potential`,
       `K⁺ channels open → the membrane depolarizes → Na⁺ channels open → the plateau ends the action potential`,
       `The membrane drifts spontaneously to threshold → Ca²⁺ enters → Na⁺ leaves → the cell repolarizes`,
       `Ca²⁺ is released from the sarcoplasmic reticulum → the membrane depolarizes → the Na⁺/K⁺ pump repolarizes the cell`],
 ans:0, why:`Contractile cells have a STABLE resting potential and must be excited by a neighbouring cell. Option 4 describes an autorhythmic cell instead — its unstable pacemaker potential drifts to threshold on its own.`},

{n:35, topic:"cardio", obj:["C2"],
 q:`In cardiac muscle, how does the action potential actually produce contraction?`,
 opts:[`The action potential travels down the T tubules and triggers Ca²⁺ influx from the extracellular fluid, which induces release of more Ca²⁺ from the sarcoplasmic reticulum; Ca²⁺ binds troponin and the myofilaments slide.`,
       `The action potential binds directly to troponin, and no calcium is involved.`,
       `Calcium comes only from the extracellular fluid; the sarcoplasmic reticulum plays no part in cardiac muscle.`,
       `The action potential makes potassium bind tropomyosin, exposing the actin binding sites.`,
       `Contraction occurs with no change in intracellular calcium, which is what sets cardiac muscle apart from skeletal muscle.`],
 ans:0, why:`Cardiac contraction is much like skeletal muscle contraction with one twist: extracellular Ca²⁺ entering through the T tubules is what triggers the SR to release its own calcium.`},

{n:36, topic:"cardio", obj:["C3"],
 q:`Which statement about what an electrocardiogram records is correct?`,
 opts:[`It shows changes in electrical activity relative to the electrodes and their placement; it does not measure the value of any action potential or membrane potential.`,
       `It measures the membrane potential of individual cardiac muscle cells directly, in millivolts.`,
       `It measures the mechanical force of each contraction rather than electrical activity.`,
       `It records the electrical activity of the SA node only.`,
       `It measures cardiac output directly, in litres per minute.`],
 ans:0, why:`An ECG is a graphic depiction of electrical activity in ALL cardiac muscle cells over time, and the tracing depends on the direction and distance of the impulse relative to each electrode. It shows rhythm disturbances — not absolute membrane voltages.`},

{n:37, topic:"cardio", hy:1, obj:["C3"],
 q:`Which ECG measurement is used to determine heart rate, and which one includes the AV nodal delay?`,
 opts:[`The R-R interval gives heart rate; the P-R interval includes the AV nodal delay.`,
       `The P-R interval gives heart rate; the R-R interval includes the AV nodal delay.`,
       `The Q-T interval gives heart rate; the S-T segment includes the AV nodal delay.`,
       `The S-T segment gives heart rate; the Q-T interval includes the AV nodal delay.`,
       `The P wave gives heart rate; the T wave includes the AV nodal delay.`],
 ans:0, why:`R-R is the time between successive R waves — one full cycle of generation and spread, so it gives rate. P-R runs from the start of P to the start of R: the time for SA-generated depolarization to spread from the atria to the ventricles, AV delay included. Q-T covers spread through the ventricular cells.`},

{n:38, topic:"cardio", obj:["C3","C4"],
 q:`On an ECG, which mechanical event follows the QRS complex?`,
 opts:[`Ventricular contraction — the electrical event always precedes the mechanical one.`,
       `Atrial contraction, since the QRS represents atrial depolarization.`,
       `Ventricular relaxation, since the QRS represents ventricular repolarization.`,
       `Closure of the semilunar valves and the second heart sound.`,
       `The AV nodal delay, which occurs after the ventricles depolarize.`],
 ans:0, why:`Depolarize, then contract. P wave → atrial contraction; QRS → ventricular contraction; T wave → ventricular relaxation. The AV delay happens between the P wave and the QRS.`},

{n:39, topic:"cardio", hy:1, obj:["C4"],
 q:`What does "cardiac cycle" mean, and what must be true about the timing of atrial and ventricular events?`,
 opts:[`All the events of one complete heartbeat — and atrial excitation and contraction must finish before ventricular contraction begins.`,
       `One respiratory cycle's worth of heartbeats — and the atria and ventricles contract simultaneously.`,
       `The interval between the two heart sounds, during which no chamber contracts.`,
       `The time it takes blood to travel all the way around the systemic circuit and back.`,
       `The period during which the SA node is refractory and cannot fire.`],
 ans:0, why:`Systole is contraction and diastole is relaxation. The whole point of the AV nodal delay is to keep atrial and ventricular contraction from overlapping.`},

{n:40, topic:"cardio", obj:["C4"],
 q:`During the ventricular ejection phase, which statement is true?`,
 opts:[`The semilunar valves are open, the AV valves are closed, and ventricular volume is falling.`,
       `The semilunar valves are closed, the AV valves are open, and ventricular volume is rising.`,
       `All four valves are closed and ventricular volume is unchanged.`,
       `The AV valves are open and blood flows from the atria straight into the aorta.`,
       `The atria are in systole while the ventricles are in diastole.`],
 ans:0, why:`Ejection starts the moment ventricular pressure exceeds arterial pressure and forces the semilunar valves open. The AV valves stayed shut from the beginning of systole, so blood has only one way to go.`},

{n:41, topic:"cardio", hy:1, obj:["C5"],
 q:`What single principle determines whether a given heart valve is open or closed at any instant?`,
 opts:[`The pressure difference across it — the valves open and close passively in response to pressure changes, ensuring one-way flow.`,
       `Direct nervous stimulation of the valve cusps by the AV node.`,
       `Contraction of the papillary muscles, which actively pull each valve open.`,
       `The concentration of calcium in the blood passing through the valve.`,
       `The SA node's rate, which sets each valve's opening interval independently.`],
 ans:0, why:`Valves are passive one-way doors driven entirely by the pressure on either side. Papillary muscles and chordae tendineae only stop the AV cusps from everting — they never pull a valve open.`},

{n:42, topic:"cardio", obj:["C5"],
 q:`When is aortic pressure highest, and what closes the aortic valve?`,
 opts:[`Aortic pressure peaks during ventricular ejection; the valve closes when ventricular pressure falls below aortic pressure and blood flowing back toward the ventricle pushes the cusps shut.`,
       `Aortic pressure peaks during isovolumetric relaxation; the valve is pulled shut by the chordae tendineae.`,
       `Aortic pressure peaks during ventricular filling; the valve closes when the atria contract.`,
       `Aortic pressure peaks during atrial systole; the papillary muscles snap the valve shut.`,
       `Aortic pressure is constant through the cycle; the valve closes on a signal from the SA node.`],
 ans:0, why:`That backflow closing the semilunar valves is the second heart sound and the start of ventricular diastole.`},

{n:43, topic:"cardio", hy:1, obj:["C6","C9"],
 q:`Contrast the effects of the two autonomic divisions on the heart.`,
 opts:[`Parasympathetic fibers release ACh, which raises K⁺ permeability and hyperpolarizes the pacemaker cells to slow the rate; sympathetic fibers release NE/E, which opens more Na⁺ and Ca²⁺ channels and speeds depolarization.`,
       `Parasympathetic fibers release norepinephrine and speed the heart; sympathetic fibers release acetylcholine and slow it.`,
       `Both divisions speed the heart, differing only in how quickly they act.`,
       `Parasympathetic stimulation raises stroke volume without changing rate; sympathetic stimulation does the reverse.`,
       `Neither division affects the heart, because the SA node is completely independent of the nervous system.`],
 ans:0, why:`Hyperpolarize a pacemaker cell and it takes longer to drift to threshold — slower rate. Open more Na⁺ and Ca²⁺ channels and it gets there faster — quicker rate.`},

{n:44, topic:"cardio", hy:1, obj:["C7"],
 q:`Which statement about cardiac output and cardiac reserve is correct?`,
 opts:[`Cardiac output is the volume each ventricle pumps per minute (HR × SV); cardiac reserve is the difference between resting and maximal cardiac output.`,
       `Cardiac output is the volume pumped with each beat; cardiac reserve is another name for stroke volume.`,
       `Cardiac output is heart rate divided by stroke volume; cardiac reserve is the volume left in the ventricle after ejection.`,
       `Cardiac output is the total blood volume in the body; cardiac reserve is the volume stored in the veins.`,
       `Cardiac output and cardiac reserve both mean the maximum output the heart can produce.`],
 ans:0, why:`Resting CO is about 5 L/min. Cardiac reserve runs about 20–25 L/min in most people and can reach roughly 40 L/min in trained athletes.`},

{n:45, topic:"cardio", obj:["C8"],
 q:`Digitalis slows the removal of calcium from the cytosol of cardiac muscle cells; calcium channel blockers reduce calcium influx. Which determinant of stroke volume are both drugs acting on?`,
 opts:[`Contractility — digitalis increases the force of contraction and calcium channel blockers reduce it.`,
       `Preload — digitalis raises venous return and calcium channel blockers lower it.`,
       `Afterload — both drugs work by changing arterial pressure.`,
       `Heart rate — neither drug can affect the force of contraction.`,
       `Cardiac reserve — both drugs raise the maximum achievable cardiac output.`],
 ans:0, why:`More cytosolic calcium means a stronger contraction at any given fiber length — that is contractility. Digitalis is used in a weakened heart for exactly this reason.`},

{n:46, topic:"cardio", obj:["C8"],
 q:`A patient loses a significant volume of blood. How does the resulting drop in venous return affect stroke volume, and why?`,
 opts:[`Stroke volume falls, because less blood returning means less ventricular stretch and a smaller end-diastolic volume to eject.`,
       `Stroke volume rises, because the ventricle has less blood to move and can eject it faster.`,
       `Stroke volume is unchanged, because it depends only on the SA node's firing rate.`,
       `Stroke volume rises, because a lower blood volume drops afterload to zero.`,
       `Stroke volume falls, because a lower blood volume raises afterload above aortic pressure.`],
 ans:0, why:`Preload is set mostly by venous return. Less filling means less stretch, which means a weaker contraction and less blood ejected per beat — the mechanism behind hypovolemic shock.`},

{n:47, topic:"cardio", obj:["C9"],
 q:`Which set of physical factors correctly matches its effect on heart rate?`,
 opts:[`Increasing age lowers heart rate; exercise and rising body temperature both raise it.`,
       `Increasing age raises heart rate; exercise and rising temperature both lower it.`,
       `All three factors lower heart rate.`,
       `All three factors raise heart rate.`,
       `Only exercise affects heart rate; age and temperature have no effect.`],
 ans:0, why:`Also on the list: epinephrine and thyroxine raise heart rate; elevated ECF K⁺ and Na⁺ lower it, while elevated ECF Ca²⁺ raises it.`},

{n:48, topic:"cardio", hy:1, obj:["C10"],
 q:`A monitor shows a resting rate of 48 beats per minute in a dizzy patient. What is that called, and what is the opposite abnormality called?`,
 opts:[`Bradycardia, under 60 bpm; the opposite is tachycardia, over 100 bpm.`,
       `Tachycardia, under 60 bpm; the opposite is bradycardia, over 100 bpm.`,
       `Fibrillation, any rate under 50 bpm; the opposite is an arrhythmia.`,
       `An arrhythmia, under 60 bpm; the opposite is a heart block.`,
       `A heart block, under 60 bpm; the opposite is an ectopic focus.`],
 ans:0, why:`Bradycardia is under 60 and tachycardia over 100. An arrhythmia is uncoordinated atrial and ventricular contraction, and fibrillation is irregular chaotic twitching of the myocardium.`},

/* ======================= BLOOD VESSELS · 16 ======================= */
{n:49, topic:"vessels", obj:["V1"],
 q:`Which statement correctly describes how the smallest vessels relate to the larger ones?`,
 opts:[`Capillaries usually connect arterioles to venules; several capillaries unite to form a venule, and several venules unite to form a vein.`,
       `Venules unite to form capillaries, which unite to form arterioles.`,
       `Capillaries connect two arterioles directly, and veins arise straight from arteries.`,
       `Arterioles arise from venules, and capillaries drain into the tunica externa.`,
       `Veins branch into venules, which branch into capillaries and then into arteries.`],
 ans:0, why:`Going out, vessels branch and get smaller; coming back, they merge and get larger. Capillaries are the hinge point where the arterial side becomes the venous side.`},

{n:50, topic:"vessels", hy:1, obj:["V2"],
 q:`Which type of capillary would you expect in a tissue where whole cells and large proteins have to cross the wall, such as the liver or bone marrow?`,
 opts:[`Sinusoid capillaries`, `Continuous capillaries`, `Fenestrated capillaries`, `Elastic capillaries`, `Muscular capillaries`],
 ans:0, why:`Three types, in order of leakiness: continuous (the most common and least permeable), fenestrated (pores, for filtration and rapid absorption), and sinusoid (widest and leakiest — liver, spleen, bone marrow). There is no such thing as an elastic or muscular capillary.`},

{n:51, topic:"vessels", obj:["V2","V7"],
 q:`Why are the arterioles described as the primary resistance vessels?`,
 opts:[`Their tunica media is heavily muscled relative to their small lumen, so constricting or dilating them changes resistance and controls how much blood enters a capillary bed.`,
       `They are the longest vessels in the body, and resistance depends mainly on vessel length.`,
       `They contain valves that intermittently block flow.`,
       `Their walls are one cell thick, which creates maximum friction.`,
       `They have the greatest total cross-sectional area of any vessel type.`],
 ans:0, why:`Lumen size is the resistance factor the body actively adjusts moment to moment, and the arterioles are where it does it — which is how blood gets redirected to whichever tissue needs it.`},

{n:52, topic:"vessels", hy:1, obj:["V2","V5"],
 q:`Which feature of veins prevents backflow, and how much of the blood do the systemic veins hold at rest?`,
 opts:[`One-way valves; at rest the systemic veins and venules hold the largest share of the blood, which is why they are called blood reservoirs.`,
       `A thick tunica media; at rest the veins hold almost no blood, since it all sits in the arteries.`,
       `Pectinate muscles; at rest the veins hold about 5% of the blood.`,
       `Fenestrations in the endothelium; at rest the veins hold about the same volume as the capillaries.`,
       `A pressure-reservoir effect from elastic fibers; the veins hold less blood than the heart itself.`],
 ans:0, why:`Venous pressure is too low to prevent backflow on its own, so veins carry valves. And because they are the reservoir, constricting them is a fast way to boost venous return.`},

{n:53, topic:"vessels", hy:1, obj:["V3"],
 q:`Which circulatory route carries blood from the digestive organs to the liver before returning it to the heart?`,
 opts:[`The hepatic portal circulation`, `The pulmonary circulation`, `The coronary circulation`, `The fetal circulation`, `The systemic arterial circulation`],
 ans:0, why:`The four circulatory routes covered in lecture are systemic, pulmonary, hepatic portal and fetal. The hepatic portal route routes nutrient-rich blood through the liver before it reaches the rest of the body.`},

{n:54, topic:"vessels", hy:1, obj:["V4"],
 q:`At the venous end of a capillary bed, which pressure dominates and what is the result?`,
 opts:[`Blood colloid osmotic pressure dominates over the now-lower blood hydrostatic pressure, so fluid is reabsorbed into the capillary.`,
       `Blood hydrostatic pressure dominates, so even more fluid filters out than at the arterial end.`,
       `Both pressures fall to zero, so no fluid moves at all.`,
       `Interstitial colloid osmotic pressure dominates, pulling fluid permanently into the tissue.`,
       `Fluid is pumped back into the capillary by active transport across the endothelium.`],
 ans:0, why:`Hydrostatic pressure drops as blood moves along the capillary, but the plasma proteins stay behind — so the inward osmotic pull wins at the venous end. When that balance fails, fluid accumulates in the tissue as edema.`},

{n:55, topic:"vessels", obj:["V4"],
 q:`Which statement about bulk flow across capillary walls is correct?`,
 opts:[`It is a passive process in which large numbers of ions and molecules move together from higher to lower pressure, and it matters most for regulating the relative volumes of blood and interstitial fluid.`,
       `It is an active process requiring ATP, and it matters most for moving oxygen into cells.`,
       `It moves single molecules independently, each down its own concentration gradient.`,
       `It occurs only in fenestrated capillaries and only during exercise.`,
       `It moves fluid from lower to higher pressure, which is why it needs carrier proteins.`],
 ans:0, why:`Diffusion handles individual solutes down their own gradients; bulk flow moves everything together down a pressure gradient, and continues as long as a pressure difference exists.`},

{n:56, topic:"vessels", obj:["V5"],
 q:`An exercising skeletal muscle automatically receives more blood flow with no change in systemic blood pressure. What is this called?`,
 opts:[`Autoregulation — a tissue adjusting its own blood flow to match its metabolic demand`,
       `The baroreflex — the medulla raising cardiac output on demand`,
       `Venous return — the skeletal muscle pump forcing blood into the tissue`,
       `Anastomosis — blood rerouting around an obstruction`,
       `Transcytosis — nutrients being ferried across the capillary in vesicles`],
 ans:0, why:`Autoregulation is local: physical and chemical stimuli inside the tissue itself adjust its blood flow to match its need for oxygen and nutrient delivery and waste removal.`},

{n:57, topic:"vessels", hy:1, obj:["V6","V1"],
 q:`Venous blood pressure is very low. What three mechanisms help return venous blood to the heart?`,
 opts:[`Valves, the respiratory pump, and the skeletal muscle pump`,
       `Pectinate muscles, the coronary sinus, and the AV valves`,
       `Capillary vasoconstriction, transcytosis, and bulk flow`,
       `Elastic recoil of the veins, the pericardial cavity, and surfactant`,
       `Baroreceptors, chemoreceptors, and the cardiovascular center`],
 ans:0, why:`Venous return is ultimately driven by the pressure the left ventricle generated, and assisted by valves plus the respiratory and skeletal muscle pumps — which is why moving your legs helps and standing still does not.`},

{n:58, topic:"vessels", obj:["V7"],
 q:`A patient with severe polycythemia has a hematocrit of 75%. What happens to vascular resistance and blood pressure?`,
 opts:[`Increased blood viscosity raises resistance, which raises blood pressure.`,
       `Increased viscosity lowers resistance, which lowers blood pressure.`,
       `Viscosity has no effect on resistance, which depends only on vessel length.`,
       `Viscosity lowers resistance because thicker blood flows in a smoother stream.`,
       `Viscosity raises resistance but lowers blood pressure, because the flow slows down.`],
 ans:0, why:`Viscosity is one of the three determinants of resistance, along with lumen size and total vessel length. Thicker blood is harder to push, so resistance and pressure both climb — and flow becomes sluggish.`},

{n:59, topic:"vessels", hy:1, obj:["V7","V5"],
 q:`Blood pressure is generated by contraction of the ventricles. Which three factors determine it?`,
 opts:[`Cardiac output, blood volume, and vascular resistance`,
       `Tidal volume, respiratory rate, and hematocrit`,
       `Vessel length, valve number, and pulse pressure`,
       `Plasma protein concentration, body temperature, and age only`,
       `Stroke volume alone, since heart rate does not affect pressure`],
 ans:0, why:`BP is determined by CO, blood volume and resistance — and since CO = HR × SV, anything that changes rate or stroke volume changes pressure too. The higher the pressure, the greater the flow.`},

{n:60, topic:"vessels", hy:1, obj:["V8"],
 q:`Which hormone pairing correctly matches the hormone to its effect on blood pressure?`,
 opts:[`Aldosterone and ADH raise blood pressure by increasing blood volume; atrial natriuretic peptide lowers it by decreasing blood volume.`,
       `Aldosterone lowers blood pressure by increasing urine output; ANP raises it by retaining fluid.`,
       `ADH lowers blood pressure by causing vasodilation; angiotensin II lowers it by vasoconstriction.`,
       `Epinephrine lowers heart rate and contractility, and so lowers blood pressure.`,
       `Nitric oxide raises blood pressure by causing widespread vasoconstriction.`],
 ans:0, why:`Three routes to change pressure. Cardiac output: NE and E raise rate and contractility. Resistance: angiotensin II, ADH, NE and E constrict, while ANP, nitric oxide and epinephrine at β₂ receptors dilate. Volume: aldosterone and ADH raise it, ANP lowers it.`},

{n:61, topic:"vessels", obj:["V9"],
 q:`You need to check a pulse at the wrist and again behind the knee. Which arteries are you palpating?`,
 opts:[`The radial artery on the lateral aspect of the wrist and the popliteal artery posterior to the knee`,
       `The brachial artery at the wrist and the femoral artery behind the knee`,
       `The ulnar artery at the wrist and the dorsalis pedis behind the knee`,
       `The radial artery at the wrist and the femoral artery behind the knee`,
       `The common carotid at the wrist and the popliteal artery behind the knee`],
 ans:0, why:`Other pulse points: superficial temporal (medial to the ear), facial (mandible, in line with the corners of the mouth), common carotid (lateral to the larynx), brachial (medial side of the biceps brachii), femoral (inferior to the inguinal ligament), dorsalis pedis (superior to the instep of the foot).`},

{n:62, topic:"vessels", obj:["V10"],
 q:`A patient goes into shock after a massive myocardial infarction leaves the heart unable to pump effectively. Which type of shock is this?`,
 opts:[`Cardiogenic shock`, `Hypovolemic shock`, `Vascular shock`, `Obstructive shock`, `Neurogenic hypertension`],
 ans:0, why:`Four types: hypovolemic (too little blood volume), cardiogenic (the pump fails), vascular (widespread vasodilation with normal volume) and obstructive (something physically blocks flow). All of them end in inadequate cardiac output.`},

{n:63, topic:"vessels", hy:1, obj:["V11"],
 q:`Which set of changes occurs in the cardiovascular system with aging?`,
 opts:[`Loss of aortic compliance, reduced cardiac muscle fiber size, progressive loss of cardiac muscular strength, a lower maximum heart rate, and increased systolic blood pressure`,
       `Increased aortic compliance, larger cardiac muscle fibers, and a higher maximum heart rate`,
       `No measurable change in the heart, with all changes confined to the veins`,
       `Decreased systolic blood pressure and increased cardiac reserve`,
       `Total loss of valve function and complete replacement of the myocardium by scar`],
 ans:0, why:`A stiffer aorta cannot absorb the ejection surge as well, so systolic pressure rises — while the pump itself gets weaker and its maximum rate falls. That combination is why cardiac reserve declines with age.`},

{n:64, topic:"vessels", obj:["V12","C10"],
 q:`Why is chronic hypertension damaging to the heart as well as to the vessels?`,
 opts:[`The elevated arterial pressure raises afterload, so the ventricle has to work harder on every beat and eventually weakens.`,
       `The elevated pressure lowers afterload, so the ventricle atrophies from disuse.`,
       `It affects the vessels only; the heart is unaffected by arterial pressure.`,
       `It lowers vascular resistance, raising stroke volume beyond what the valves can handle.`,
       `It makes the SA node stop firing, which is why hypertension always presents as bradycardia.`],
 ans:0, why:`Afterload is the pressure the ventricle must beat to eject, so hypertension means a permanently harder workload. Hypertension also sits alongside atherosclerosis, inflammation and blood stasis as a risk factor for thromboembolic disease.`},

/* ==================== RESPIRATORY SYSTEM · 16 ==================== */
{n:65, topic:"resp", obj:["R1","R4"],
 q:`Besides supplying oxygen and removing carbon dioxide, which list gives additional functions of the respiratory system?`,
 opts:[`Helps regulate blood pH, houses the receptors for smell, filters/warms/moistens inspired air, and produces sound`,
       `Produces surfactant for the plasma, stores calcium, and generates red blood cells`,
       `Absorbs nutrients, secretes digestive enzymes, and stores bile`,
       `Produces erythropoietin, filters nitrogenous waste, and regulates blood glucose`,
       `Provides the body's only route for heat loss and produces all of its antibodies`],
 ans:0, why:`The main job is supplying O₂ for cellular respiration and disposing of CO₂ — but the system also buffers blood pH, carries the olfactory receptors, conditions inspired air, and produces the sounds of speech.`},

{n:66, topic:"resp", hy:1, obj:["R1"],
 q:`Which structures make up the upper respiratory system, and which the lower?`,
 opts:[`Upper: nose and nasal cavity, paranasal sinuses, pharynx, larynx. Lower: trachea, bronchi and their branches, lungs and alveoli.`,
       `Upper: trachea and bronchi. Lower: nose, pharynx and larynx.`,
       `Upper: nose and trachea. Lower: pharynx, larynx and lungs.`,
       `Upper: everything in the conducting zone. Lower: everything in the respiratory zone.`,
       `Upper: the right lung. Lower: the left lung.`],
 ans:0, why:`Careful — upper/lower is a different split from conducting/respiratory zone. The larynx marks the boundary: everything above it is upper respiratory, the trachea and below is lower.`},

{n:67, topic:"resp", hy:1, obj:["R2","R4"],
 q:`Which statement about the pharynx is correct?`,
 opts:[`It is a shared passageway for both air and food, acts as a resonating chamber for speech, houses the tonsils, and is divided into nasopharynx, oropharynx and laryngopharynx.`,
       `It carries air only, and is divided into the nasopharynx and the trachea.`,
       `It carries food only, and its three regions are the glottis, epiglottis and larynx.`,
       `It is a site of gas exchange and is lined with simple squamous epithelium.`,
       `It is a single undivided chamber containing the vocal folds.`],
 ans:0, why:`Infected, swollen adenoids in the nasopharynx can block airflow and force mouth breathing — so air reaches the lungs unwarmed, unmoistened and unfiltered, and chronic enlargement disturbs both speech and sleep.`},

{n:68, topic:"resp", obj:["R3","R11"],
 q:`Why can an infection that begins as rhinitis spread to the throat, chest, tear ducts and sinuses?`,
 opts:[`The nasal mucosa is continuous with the mucosa of the rest of the respiratory tract and with the passages to the sinuses and tear ducts.`,
       `The nasal cavity drains directly into the pulmonary veins.`,
       `Nasal mucus is carried to those sites by the lymphatic capillaries of the nose.`,
       `The nasal cavity shares one continuous epithelial layer with the alveoli themselves.`,
       `Sinus infections are only ever bacterial, and the bacteria travel through the bloodstream.`],
 ans:0, why:`Rhinitis is inflammation of the nasal mucosa, and because that mucosa is continuous, infection travels nose → throat → chest. Blocked sinus passageways can then let air be absorbed, creating a partial vacuum — the classic sinus headache.`},

{n:69, topic:"resp", hy:1, obj:["R3","R5"],
 q:`The trachea runs from the larynx to about the fifth thoracic vertebra, where it divides. Which statement about the primary bronchi is correct?`,
 opts:[`The right primary bronchus is wider, shorter and more vertical than the left, and each enters its lung at the hilus.`,
       `The left primary bronchus is wider, shorter and more vertical than the right.`,
       `Both primary bronchi are identical in size and angle.`,
       `The primary bronchi enter the lungs at the apex, just deep to the clavicle.`,
       `The primary bronchi contain no cartilage at all — only smooth muscle.`],
 ans:0, why:`The hilus is the medial depression where the bronchus and vessels enter the lung. Because the right bronchus is wider and more vertical, an aspirated object is more likely to end up in the right lung.`},

{n:70, topic:"resp", hy:1, obj:["R3","R1"],
 q:`Which sequence correctly follows the bronchial tree from the trachea down to the site of gas exchange?`,
 opts:[`Primary bronchi → secondary bronchi → tertiary bronchi → bronchioles → terminal bronchioles → respiratory bronchioles → alveolar ducts → alveolar sacs → alveoli`,
       `Primary bronchi → bronchioles → tertiary bronchi → secondary bronchi → alveoli`,
       `Alveolar ducts → terminal bronchioles → secondary bronchi → primary bronchi → alveoli`,
       `Trachea → alveolar sacs → respiratory bronchioles → tertiary bronchi → alveoli`,
       `Primary bronchi → terminal bronchioles → secondary bronchi → alveolar ducts → alveoli`],
 ans:0, why:`About 25 generations of branching. Bronchioles are under 1 mm in diameter and terminal bronchioles under 0.5 mm; the respiratory zone begins where terminal bronchioles feed into respiratory bronchioles.`},

{n:71, topic:"resp", obj:["R4","R8"],
 q:`What forms the respiratory membrane, and how do gases cross it?`,
 opts:[`The alveolar wall and the capillary wall — two layers of simple squamous epithelium — and gases cross by diffusion.`,
       `The pleural membranes, and gases cross by active transport.`,
       `Pseudostratified ciliated columnar epithelium, and gases cross by bulk flow.`,
       `The alveolar wall alone, and gases are ferried across by surfactant.`,
       `The basement membrane of the bronchioles, and gases cross by transcytosis.`],
 ans:0, why:`Two squamous layers back to back is about as thin as a barrier gets — which is exactly what makes diffusion fast enough. Oxygen crosses into the blood, carbon dioxide crosses into the alveolus.`},

{n:72, topic:"resp", obj:["R5"],
 q:`The lungs are perfused by two circulations. Which statement is correct?`,
 opts:[`Pulmonary arteries bring systemic venous blood to be oxygenated, while bronchial arteries off the aorta bring oxygenated blood to nourish the lung tissue itself.`,
       `Pulmonary arteries nourish the lung tissue, while bronchial arteries carry blood to be oxygenated.`,
       `Both circulations carry deoxygenated blood, which is why the lungs get so little oxygen.`,
       `The lungs have only the pulmonary circulation and no systemic supply at all.`,
       `The bronchial arteries arise from the pulmonary trunk and specifically supply the alveoli.`],
 ans:0, why:`The bronchial circulation is part of the systemic circuit and supplies all lung tissue except the alveoli. Bronchial veins anastomose with pulmonary veins, and the pulmonary veins carry most venous blood back to the heart.`},

{n:73, topic:"resp", hy:1, obj:["R6"],
 q:`During quiet exhalation, what happens?`,
 opts:[`The diaphragm and external intercostals relax, thoracic volume falls, intrapulmonary pressure rises above atmospheric, and air flows out passively.`,
       `The diaphragm contracts and flattens, forcing air out of the lungs.`,
       `The abdominal muscles must contract, because quiet exhalation is always active.`,
       `Intrapulmonary pressure falls below atmospheric, drawing air outward.`,
       `The alveoli actively contract, squeezing air into the bronchioles.`],
 ans:0, why:`Quiet exhalation is passive — muscles relax and the elastic lungs and chest wall recoil. Forced exhalation is the one that recruits abdominal and internal intercostal muscles.`},

{n:74, topic:"resp", obj:["R6"],
 q:`Atmospheric pressure at sea level is 760 mmHg. If a respiratory pressure is given as −2 mmHg, what is the actual pressure?`,
 opts:[`758 mmHg — respiratory pressures are always stated relative to atmospheric pressure`,
       `2 mmHg — very nearly a vacuum`,
       `762 mmHg`,
       `−2 mmHg absolute, which would collapse the lung instantly`,
       `380 mmHg — half of atmospheric pressure`],
 ans:0, why:`"Negative pressure" in respiratory physiology just means below atmospheric: −1 mmHg = 759, +1 mmHg = 761, and 0 mmHg = 760.`},

{n:75, topic:"resp", hy:1, obj:["R7"],
 q:`Which definition of a lung volume is correct?`,
 opts:[`Tidal volume is the amount of air moved in and out with each normal quiet breath.`,
       `Tidal volume is the maximum air that can be forcibly exhaled after a normal breath.`,
       `Inspiratory reserve volume is the air remaining in the lungs after maximal exhalation.`,
       `Expiratory reserve volume is the air inhaled beyond a normal breath.`,
       `Residual volume is the total amount of exchangeable air.`],
 ans:0, why:`TV = a normal breath. IRV = the extra you can pull in beyond it. ERV = the extra you can push out after it. RV = what stays no matter what. VC = TV + IRV + ERV, and TLC = VC + RV.`},

{n:76, topic:"resp", obj:["R7"],
 q:`What does minute ventilation measure, and what test is used to assess lung function?`,
 opts:[`The total volume of air inhaled and exhaled each minute; lung function is assessed by spirometry.`,
       `The volume of blood passing through the lungs each minute; it is assessed by an ECG.`,
       `The number of breaths per minute only; it is assessed with a stethoscope.`,
       `The residual volume; it is measured directly by a spirometer.`,
       `The partial pressure of oxygen in arterial blood; it is measured with a spirometer.`],
 ans:0, why:`Spirometry provides the volumes and capacities used to assess lung function. Minute ventilation is the total volume moved per minute — essentially tidal volume times respiratory rate.`},

{n:77, topic:"resp", obj:["R8"],
 q:`Air is a mixture of gases. What is meant by the partial pressure of one of them?`,
 opts:[`The share of the mixture's total pressure contributed by that individual gas.`,
       `The pressure the gas exerts only after it has dissolved in the blood plasma.`,
       `The total pressure of the mixture divided by the number of gases present, regardless of their amounts.`,
       `The pressure needed to force the gas across the respiratory membrane by active transport.`,
       `The difference between atmospheric and intrapleural pressure.`],
 ans:0, why:`Nitrogen, oxygen, water vapour, carbon dioxide and the rest each contribute part of the total. Each gas then moves independently from higher to lower partial pressure — which is what drives external and internal respiration.`},

{n:78, topic:"resp", hy:1, obj:["R9"],
 q:`How is most oxygen carried in the blood?`,
 opts:[`About 98.5% bound to hemoglobin inside the red blood cells, as oxyhemoglobin`,
       `About 98.5% dissolved in the plasma as free O₂`,
       `About 70% as bicarbonate ions`,
       `About 23% as carbaminohemoglobin, with the rest dissolved in plasma`,
       `Entirely bound to albumin in the plasma`],
 ans:0, why:`Oxygen rides on hemoglobin — ~98.5% of it. Carbon dioxide is the gas that splits three ways: ~70% bicarbonate, ~23% carbaminohemoglobin, ~7% dissolved in plasma.`},

{n:79, topic:"resp", obj:["R10"],
 q:`Which statement about the neural control of breathing is correct?`,
 opts:[`The medulla sets the basic respiratory rhythm and the pons smooths it out; the phrenic and intercostal nerves drive the muscles, and stretch receptors in the bronchioles and alveoli signal the control centers to initiate expiration.`,
       `The pons sets the basic rhythm and the medulla smooths it; the vagus nerve alone drives the muscles.`,
       `The cerebral cortex is the only control center, which is why breathing is entirely voluntary.`,
       `The cerebellum sets the rhythm, and stretch receptors in the aorta initiate inspiration.`,
       `Breathing is controlled by the SA node, in step with the heart rate.`],
 ans:0, why:`Medulla = rhythm, pons = smoothing, phrenic and intercostal nerves = the muscles. Chemically, CO₂ acting on the medulla is the main driver, and O₂ changes are detected by chemoreceptors in the aorta and carotid arteries.`},

{n:80, topic:"resp", hy:1, obj:["R11"],
 q:`Which statement about the effect of smoking on the airway is correct?`,
 opts:[`Smoking inhibits and eventually destroys the cilia, so coughing becomes the only way to keep mucus from accumulating in the lungs; ciliary function usually recovers within a few weeks of quitting.`,
       `Smoking destroys the alveolar macrophages but leaves the cilia intact.`,
       `Smoking increases ciliary beating, which is why smokers clear mucus more efficiently.`,
       `Smoking damages only the alveoli; the trachea is unaffected.`,
       `Ciliary damage from smoking is permanent and never recovers after quitting.`],
 ans:0, why:`The ciliated pseudostratified epithelium of the trachea normally sweeps mucus upward. Destroy the cilia and coughing is all that is left — which is why the morning "smoker's cough" fades once ciliary function returns.`},
];
