/* BIOL 40B — Lecture Exam 2 · histology mini-round (20 questions)
   The microscopic-anatomy material from the five Exam 2 decks, asked the way a lecture
   exam asks it: you're given the description of what's under the objective and you pick
   what it is (or what it does). Blood smear, cardiac muscle, vessel walls, airway
   epithelium, alveoli.

   Same format and convention as the exam banks: correct option authored first, engine
   shuffles the display order. */
const HISTO = [

{n:1, topic:"blood", hy:1, obj:["B6"],
 q:`On a stained blood smear you find the most numerous white cell: a multi-lobed nucleus with very fine, pale granules in the cytoplasm. What is it, and what does it do?`,
 opts:[`Neutrophil — a phagocyte, first on the scene of an infection, and it triggers inflammation.`,
       `Eosinophil — associated with allergies and parasitic infections.`,
       `Basophil — it contains and releases histamine.`,
       `Lymphocyte — it provides specific immune defense.`,
       `Monocyte — it enters tissue and matures into a macrophage.`],
 ans:0, why:`Neutrophils are 60–70% of the WBCs, so on a smear they are what you see most. The multi-lobed nucleus is the giveaway — the older name "polymorphonuclear" describes exactly that.`},

{n:2, topic:"blood", obj:["B6"],
 q:`A granulocyte on the smear has a bilobed nucleus and cytoplasm packed with large red-orange granules. It makes up only 1–4% of the white cells. What is it?`,
 opts:[`Eosinophil`, `Neutrophil`, `Basophil`, `Lymphocyte`, `Monocyte`],
 ans:0, why:`Eosinophils stain with eosin — hence the red-orange granules — and are the granulocyte tied to allergies and parasitic infections.`},

{n:3, topic:"blood", obj:["B6"],
 q:`The rarest white cell on the smear — well under 1% — has deep blue-purple granules so dense they obscure the nucleus. What is it, and what does it release?`,
 opts:[`Basophil — it contains and releases histamine.`,
       `Eosinophil — it releases antibodies against parasites.`,
       `Neutrophil — it releases digestive enzymes for phagocytosis.`,
       `Monocyte — it releases prostacyclin and nitric oxide.`,
       `Platelet — it releases clotting factors.`],
 ans:0, why:`Basophils are under 1% of WBCs, which makes them genuinely hard to find on a slide. Their granules hold histamine, the mediator behind allergic vasodilation.`},

{n:4, topic:"blood", obj:["B6"],
 q:`An agranulocyte on the smear is the smallest white cell present: a large round nucleus filling nearly the whole cell, with only a thin rim of pale blue cytoplasm. What is it?`,
 opts:[`Lymphocyte`, `Monocyte`, `Neutrophil`, `Eosinophil`, `Erythrocyte`],
 ans:0, why:`Lymphocytes are the second most abundant WBC (25–33%) and look like a nucleus with barely any cytoplasm. They are the B cells, T cells and NK cells of specific immunity.`},

{n:5, topic:"blood", obj:["B6"],
 q:`The largest white cell on the smear has an indented, kidney-shaped nucleus and abundant grey-blue cytoplasm with no obvious granules. What is it, and what becomes of it?`,
 opts:[`Monocyte — it leaves the blood, enters the tissues, and matures into a macrophage.`,
       `Lymphocyte — it matures into a plasma cell inside the bloodstream.`,
       `Neutrophil — it matures into a natural killer cell in the spleen.`,
       `Basophil — it matures into a mast cell in the red bone marrow.`,
       `Megakaryocyte — it fragments into platelets while still in circulation.`],
 ans:0, why:`Monocyte = biggest WBC, kidney-bean nucleus, agranular. Its whole job happens after it leaves the blood, as a tissue macrophage.`},

{n:6, topic:"blood", hy:1, obj:["B2","B4"],
 q:`The overwhelming majority of cells on the smear are small, pale-centered discs with no nucleus at all. Why is the centre pale, and why is there no nucleus?`,
 opts:[`The cells are biconcave, so the thin centre lets more light through; erythrocytes eject their nucleus and organelles as they mature, which leaves room for hemoglobin.`,
       `The pale centre is a vacuole holding oxygen; the nucleus has migrated to the cell edge.`,
       `The cells were damaged in preparation; healthy erythrocytes are spherical and nucleated.`,
       `The centre is pale because hemoglobin is concentrated there; the nucleus is present but too small to see.`,
       `They are platelets, which are always anucleate and biconcave.`],
 ans:0, why:`That pale bull's-eye is the classic biconcave RBC. No nucleus and no organelles means ~97% of the cell volume (water aside) can be hemoglobin — and the cell can't consume the O₂ it carries.`},

{n:7, topic:"blood", obj:["B7"],
 q:`Scattered among the red cells are tiny purple-staining fragments, far smaller than any of the white cells and with no nucleus. What are they, and where did they come from?`,
 opts:[`Platelets — irregularly shaped cell fragments shed from megakaryocytes in the red bone marrow.`,
       `Reticulocytes — immature red cells still carrying ribosomes.`,
       `Basophil granules that have been released into the plasma.`,
       `Fibrin threads that formed as the smear dried.`,
       `Bacteria, which is why a normal smear always shows some.`],
 ans:0, why:`Platelets run 150,000–400,000/µL, so a normal smear has plenty. They are fragments, not cells — which is why they have no nucleus and no regular shape.`},

{n:8, topic:"blood", obj:["B4","B7"],
 q:`A red bone marrow specimen shows an enormous cell with a huge multi-lobed nucleus, far larger than anything in circulating blood. What is it, and what arises from it?`,
 opts:[`A megakaryocyte — platelets pinch off from it.`,
       `A hemocytoblast — every leukocyte arises directly from it without dividing.`,
       `A reticulocyte — it matures into an erythrocyte in the bloodstream.`,
       `A macrophage — it phagocytizes worn-out erythrocytes in the marrow.`,
       `An osteocyte — it maintains the bony matrix around the marrow cavity.`],
 ans:0, why:`All blood cells arise from a common stem cell (hemocytoblast) in red bone marrow. The megakaryocyte is the giant descendant whose cytoplasm fragments into platelets.`},

{n:9, topic:"heart", hy:1, obj:["H4","C1"],
 q:`A muscle specimen shows short, branched, striated cells, each with one central nucleus, joined end-to-end by dark-staining bands. What tissue is it, and what are the bands?`,
 opts:[`Cardiac muscle; the bands are intercalated discs, which anchor the cells and let ions pass through gap junctions.`,
       `Skeletal muscle; the bands are Z discs marking the ends of each sarcomere.`,
       `Smooth muscle; the bands are dense bodies anchoring the intermediate filaments.`,
       `Cardiac muscle; the bands are tendinous insertions that transmit force between cells.`,
       `Skeletal muscle; the bands are the intercalated discs unique to voluntary muscle.`],
 ans:0, why:`Three features together identify cardiac muscle on a slide: striations (so not smooth muscle), branching with a single central nucleus (so not skeletal, which is long, unbranched and multinucleate), and intercalated discs.`},

{n:10, topic:"heart", obj:["H4"],
 q:`Compared with a skeletal muscle specimen, cardiac muscle shows a strikingly large number of mitochondria. What does that tell you about the tissue?`,
 opts:[`It relies almost exclusively on aerobic respiration, so it cannot function without a constant oxygen supply.`,
       `It relies on anaerobic glycolysis, which is why it can work through long periods of ischemia.`,
       `The mitochondria store calcium for contraction, replacing the sarcoplasmic reticulum.`,
       `The mitochondria let cardiac muscle cells divide and replace themselves after a heart attack.`,
       `The mitochondria are the source of the striations seen under the microscope.`],
 ans:0, why:`Cardiac muscle has more mitochondria than skeletal muscle and a correspondingly greater dependence on oxygen — which is precisely why coronary blockage kills myocardium so quickly. It is adaptable about fuel (glucose, fatty acids, lactic acid) but not about oxygen.`},

{n:11, topic:"heart", obj:["H1"],
 q:`The innermost lining of a heart chamber is a thin sheet of simple squamous epithelium that also covers the valve surfaces. What is this layer called, and what is it continuous with?`,
 opts:[`The endocardium — it is continuous with the endothelial lining of the blood vessels.`,
       `The epicardium — it is continuous with the fibrous pericardium.`,
       `The myocardium — it is continuous with the smooth muscle of the tunica media.`,
       `The visceral pericardium — it is continuous with the parietal pleura.`,
       `The tunica externa — it is continuous with the connective tissue of the mediastinum.`],
 ans:0, why:`Endocardium lines the chambers and covers the cardiac skeleton of the valves, and it runs seamlessly into the endothelium of the great vessels — so the blood never touches anything but endothelium anywhere in the circuit.`},

{n:12, topic:"vessels", hy:1, obj:["V2"],
 q:`Two vessels appear side by side in cross-section. One has a thick, muscular wall and a round open lumen; the other has a thin wall and a flattened, collapsed lumen. Which is which, and why?`,
 opts:[`The round, thick-walled one is the artery — its heavy tunica media holds the lumen open; the collapsed thin-walled one is the vein.`,
       `The round, thick-walled one is the vein — veins have the thicker tunica media of the two.`,
       `The collapsed one is the artery, because arterial pressure drops to zero in a fixed specimen.`,
       `They cannot be distinguished histologically; only their location in the body identifies them.`,
       `The round one is a capillary and the collapsed one is an arteriole.`],
 ans:0, why:`This is the classic artery-vein pair. The artery's thick smooth-muscle-and-elastic tunica media keeps it round even in a fixed section; the vein has a thinner interna and media, a thicker externa, and collapses.`},

{n:13, topic:"vessels", hy:1, obj:["V2"],
 q:`A vessel wall in cross-section consists of nothing but a single layer of flat cells sitting on a basement membrane. What vessel is it, and what does that structure make possible?`,
 opts:[`A capillary — a wall that thin permits exchange of nutrients and wastes between blood and tissue cells.`,
       `An arteriole — a wall that thin lets it constrict and dilate rapidly.`,
       `A venule — a wall that thin lets valves form within it.`,
       `An elastic artery — a wall that thin lets it act as a pressure reservoir.`,
       `A lymphatic vessel — a wall that thin lets it absorb whole cells.`],
 ans:0, why:`One endothelial layer plus a basement membrane is the capillary, and that is exactly why capillaries are the only vessels where exchange happens.`},

{n:14, topic:"vessels", obj:["V2","V3"],
 q:`A large artery near the heart shows a tunica media dominated by wavy sheets of elastic fibers with relatively little smooth muscle. Which artery type is this, and what is its function?`,
 opts:[`An elastic (conducting) artery — it acts as a pressure reservoir, absorbing the surge of ventricular ejection.`,
       `A muscular (distributing) artery — it directs blood to specific body regions.`,
       `An arteriole — it is the main site of vascular resistance.`,
       `A sinusoid — it allows whole cells to leave the bloodstream.`,
       `A venule — it collects blood from several capillaries.`],
 ans:0, why:`Elastic arteries are large with more elastic fiber and less smooth muscle; muscular arteries are medium-sized with the ratio reversed. The elastic ones stretch with each systole and recoil during diastole, smoothing out flow.`},

{n:15, topic:"resp", hy:1, obj:["R3"],
 q:`An airway specimen shows tall ciliated pseudostratified columnar epithelium with scattered goblet cells, and a wall supported by plates of hyaline cartilage. Which structure is it?`,
 opts:[`The trachea`,
       `An alveolus`,
       `A terminal bronchiole`,
       `The epiglottis`,
       `A pulmonary capillary`],
 ans:0, why:`Ciliated pseudostratified columnar epithelium with goblet cells plus hyaline cartilage = trachea (16–20 C-shaped rings). Goblet cells make the mucus and the cilia sweep it upward — the pairing smoking destroys.`},

{n:16, topic:"resp", obj:["R3","R5"],
 q:`A small airway in the lung has cuboidal epithelium, sparse cilia, no cartilage at all, and a prominent ring of smooth muscle. What is it, and what is the functional significance of that smooth muscle?`,
 opts:[`A bronchiole — the smooth muscle lets it provide substantial resistance to airflow, and it is what constricts or dilates the airway.`,
       `The trachea — the smooth muscle replaces the cartilage rings during inhalation.`,
       `An alveolar duct — the smooth muscle actively pumps air into the alveoli.`,
       `A pulmonary arteriole — the smooth muscle regulates blood flow rather than airflow.`,
       `The larynx — the smooth muscle tenses the vocal folds.`],
 ans:0, why:`As the airways get smaller, cartilage gives way to elastic fibers and smooth muscle increases, and the epithelium shifts from pseudostratified columnar to cuboidal with fewer cilia and goblet cells. Parasympathetic fibers constrict bronchioles; sympathetic fibers dilate them.`},

{n:17, topic:"resp", hy:1, obj:["R3","R4"],
 q:`Under the microscope, lung tissue looks like a sponge of thin-walled air spaces. Two cell types line each space: a flat squamous cell forming most of the surface, and a rounder cell scattered among them. What are they?`,
 opts:[`Type I alveolar cells form the thin squamous gas-exchange surface; type II alveolar cells are the rounder cells that secrete surfactant.`,
       `Type I cells secrete surfactant; type II cells form the squamous exchange surface.`,
       `Goblet cells form the exchange surface; ciliated cells secrete surfactant.`,
       `Both cell types are alveolar macrophages at different stages of maturity.`,
       `Both are endothelial cells belonging to the pulmonary capillaries, not the alveolus.`],
 ans:0, why:`The thin squamous type I cells are what make the respiratory membrane diffusible; the cuboidal type II cells make surfactant, which lowers surface tension so the alveoli do not collapse. Alveolar macrophages are the third population, wandering the air space eating debris.`},

{n:18, topic:"resp", obj:["R3","R8"],
 q:`The respiratory membrane in a lung section is remarkably thin. How many cell layers does a molecule of oxygen actually cross to get from alveolar air into the blood?`,
 opts:[`Two layers of simple squamous epithelium — the alveolar wall and the capillary wall — plus their fused basement membranes.`,
       `Five layers, including ciliated pseudostratified epithelium and a layer of smooth muscle.`,
       `One layer, because the alveolus and the capillary share a single common cell.`,
       `Three layers of stratified squamous epithelium, which is why diffusion is slow.`,
       `Oxygen does not cross cells at all — it is carried across in vesicles by transcytosis.`],
 ans:0, why:`The respiratory membrane is the alveolar wall plus the capillary wall — two simple squamous layers — and gas crosses purely by diffusion, driven by partial-pressure gradients.`},

{n:19, topic:"resp", hy:1, obj:["R3"],
 q:`Two cartilage specimens are compared: one from the epiglottis and one from a tracheal ring. How do they differ, and why does it matter?`,
 opts:[`The epiglottis is elastic cartilage, which can bend to fold over the laryngeal inlet during swallowing; the tracheal rings are hyaline cartilage, which is stiff enough to keep the airway from collapsing.`,
       `The epiglottis is hyaline cartilage and the tracheal rings are elastic — the reverse of the above.`,
       `Both are fibrocartilage, and the difference is only in thickness.`,
       `The epiglottis is bone by adulthood; the trachea remains cartilage.`,
       `Both are elastic cartilage, which is why the trachea collapses during forced exhalation.`],
 ans:0, why:`Function follows tissue type. The epiglottis has to flex, so it is elastic cartilage; the trachea has to stay open, so it gets rigid hyaline rings — C-shaped and incomplete so the esophagus can bulge forward behind it.`},

{n:20, topic:"resp", obj:["R3","R5"],
 q:`Besides the air spaces themselves, a lung section is largely made of a loose, fibrous supporting tissue. What is it called, and what property does it give the lung?`,
 opts:[`Stroma — elastic connective tissue, which is what makes the lungs elastic and spongy.`,
       `Surfactant — a lipid layer, which is what makes the lungs rigid.`,
       `Pleura — a serous membrane, which fills the space between the alveoli.`,
       `Hyaline cartilage — which is what holds every alveolus open.`,
       `Smooth muscle — which actively expands the lungs during inhalation.`],
 ans:0, why:`Lungs are mostly alveoli; the rest is stroma, elastic connective tissue. That elasticity is what makes quiet exhalation passive — the stretched lung simply recoils.`},
];
